package ind.apptech.captionsforinstagram.fragment;

import android.content.Context;
import android.net.ConnectivityManager;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.RecyclerView;
import androidx.recyclerview.widget.StaggeredGridLayoutManager;

import ind.apptech.captionsforinstagram.Shayri_Adapt;
import com.apptech.captionsforinstagram.R;

import java.util.ArrayList;

public class Attitude_fragment extends Fragment {

    RecyclerView englishlists;
    private RecyclerView.LayoutManager layoutManager;
    Shayri_Adapt rjptadapter;
    ArrayList<String> englist = new ArrayList<>();
    LinearLayout Net_connection;

    public Attitude_fragment() {
        // Required empty public constructor
    }

    public static Attitude_fragment newInstance(String param1, String param2) {
        Attitude_fragment fragment = new Attitude_fragment();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.hindi_shayri, container, false);

        englishlists = (RecyclerView) view.findViewById(R.id.English_list);
        Net_connection = view.findViewById(R.id.Net_connection);
        layoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.VERTICAL);
        englishlists.setLayoutManager(layoutManager);
        englist = new ArrayList<>();

        englist.add("Don't need to explain myself, I know I'm right.");
        englist.add("I define my own life. I don't let people write my script.");
        englist.add("LEGENDS don’t die.. I am a LIVING EXAMPLE!");
        englist.add("My attitude depends on the people in front of me.");
        englist.add("I’m nobody, nobody is perfect, and therefore I’m perfect.");
        englist.add("Don't Copy My Style.");
        englist.add("Someone asked me what is UR attitude... then i simply replied BEING SINGLE IS MY ATTITUDE");
        englist.add("Excellence is not a skill, It is an attitude.");
        englist.add("If a plan didn't work, Alphabet has 25 more letters.");
        englist.add("My Life, My Choices, My Mistakes, My Lessons, Not your business...");
        englist.add("I never dreamed about success. I worked for it.");
        englist.add("My life, My rules My Attitude!!!");
        englist.add("People say nothing’s impossible, but I do nothing everyday.");
        englist.add("No, I'm not feeling violent, I'm feeling creative with weapons.");
        englist.add("Be yourself and you can be anything.");
        englist.add("Your whatsapp status say's online .. If your online then, why aren't you msg me!");
        englist.add("The road to success is always under construction.");
        englist.add("I don't need to explain myself because, I know I'm right.");
        englist.add("I don't hate Peoples, I just love Peoples who loves me.");
        englist.add("I always arrive late at office but I make it by leaving early.");
        englist.add("Take me as I am or watch me as I go.");
        englist.add("The greatest pleasure in life is doing the things people say you can't ;)");
        englist.add("You will find a girl prettier than me, smarter than me, and funnier than me, but you will never find a girl just like me.");
        englist.add("My life, my rule, that's my attitude..");
        englist.add("Dear Teacher, I talk to everyone, so moving my seat wont help. Sincerely, Student");
        englist.add("Please don't get confused between my my attitude & personality!");
        englist.add("I'm not lazy, I'm a master of energy conservation.");
        englist.add("i am what i am.. i will never try to be some one else.");
        englist.add("Many a man owes his success to his first wife and his second wife to his success.");
        englist.add("Apni to bass ek hi wish hai.. Ser pe Taaj.. Sath me koi Khass Aur is kamini duniya pe Raajjj!!");
        englist.add("My Attitude : I Don't Like To Take Right Decision.. I Take Decisions And Make Them Right.");
        englist.add("Smile infront of those who hates you – It kills them.");
        englist.add("The biggest slap to your enemies is your success");
        englist.add("Love me ?? Great. Hate me ?? Even Better. Don't know me ?? Don't judge me !!");
        englist.add("I'm nobody's second option. better you either CHOOSE me, or you lose me. :/");
        englist.add("Born to express not to impress.");
        englist.add("I am hot dude with cool attitude");
        englist.add("I dint change, i just grew up. You should try it once ;)");
        englist.add("i don't have an attitude problem. You have a problem with my attitude : ) Don't like it get over it Lol");
        englist.add("Success is not easy and is certainly not for lazy.");
        englist.add("Beauty is like Moon, looks much better at Night.");
        englist.add("My BACK is not a VOICEMAIL, so better say it on my FACE.");
        englist.add("Your attitude can make all the difference in how your day will begin and end.");
        englist.add("Best way to deal with haters, Keep calm, and stay classy.");
        englist.add("I enjoy when people show Attitude to me because it shows that they need an Attitude to impress me!");
        englist.add("May my enemies live a long life to see my success.");
        englist.add("Anyone who has never made a mistake has never tried anything new.");
        englist.add("Rise up and attack the day with enthusiasm.");
        englist.add("Baat unhi ki hoti hai jinmain koi baat hoti hai.");
        englist.add("There is no market for YOUR EMOTIONS, so never advertise your FEELINGS just display YOUR ATTITUDE.");
        englist.add("It's the good girls who keep diaries;the bad girls never have the time.I dint change, i just grew up. You should try it once ;)");
        englist.add("If you dislike me, remember: it's mind over matter. I don't mind and you don't matter!");
        englist.add("Not always 'Available'.. Try your Luck.");
        englist.add("It's not my attitude it's my style.");
        englist.add("The problem is not the problem; the problem is your attitude about the problem.");
        englist.add("If they hates you for no reason- Give them 1");
        englist.add("Status Unavailable! Check Later.");
        englist.add("If you want me to control my temper.. You need to control your stupidity.");
        englist.add("Yes, I have made mistakes because life didn't come with 'USER MANUAL and INSTRUCTIONS'!");
        englist.add("If you can't handle me at my worst, then you don't deserve me at my best. if you can't accept my past, then you won't see yourself in my future.");
        englist.add("I am learn from My Mistake! Without Mistake We Can't Learn Best.");
        englist.add("You have a problem with me. I'm pretty sure a status on Facebook won't fix it.");
        englist.add("I'm Not Sad For Being Single Rather I'm Thinking Of Her Who Is Single Because Of Me.. :P");
        englist.add("Why is 'Monday' so far from 'Friday' and 'Friday' so near to 'Monday'??");
        englist.add("Can you do me a favor? Take a picture of yourself, and send it to me. I am playing cards and seem to be missing the Joker.");
        englist.add("My attitude is based on how you treat me.");
        englist.add("In language learning, it is attitude, not aptitude, that determines success.");
        englist.add("Stop complaining if you don't like how things are. Take control.. Decide how YOU are going to change it.. Think positive.. Get rid of the drama.. Move Forward.");
        englist.add("I keep ego and attitude always in my pockets, so that I can use it when my self-respect and sentiments are being tested by people.");
        englist.add("Forget the haters...cause some body loves you");
        englist.add("If some one hate you without reason then Give the reason to him!");
        englist.add("Eat right, exercise, die anyway.");
        englist.add("A bad attitude is like a flat tire. If you don't change it, you'll never go anywhere.");
        englist.add("I Don't Care About Popularity. I Live In Reality. Based On Originality. Forget Looks. I Respect Personality");
        englist.add("I was told I should have a positive attitude. Well, I am positive that I have an attitude.");
        englist.add("So you're checking my status.. :D");
        englist.add("The quickest way to double your money is to FOLD it in half and put it back in your pocket.");
        englist.add("Don't make a girl fall for you if you have no intention of catching HER. :-)");
        englist.add("Silent people have the loudest minds.");
        englist.add("Better to remain silent and be thought a fool, than to speak and remove all doubt.");
        englist.add("Cling to your imperfections, they are what make you unique.");
        englist.add("People who tolerate me on the daily basis! are real heroes in my eye.");
        englist.add("I'm not heartless, I just learned how to use my heart LESS.");
        englist.add("Adopt a right attitude make you the negative thinking to positive thinking!");
        englist.add("Readers are plentiful: thinkers are rare.");
        englist.add("Phones are better than GF, At least we can switch it off.");
        englist.add("There are three sides to an argument.. my side, your side and the right side.");
        englist.add("The longer the title the less important the job.");
        englist.add("Attitudes have the power to lift us up or tear us down.");
        englist.add("Please don't get confused between my personality & my attitude My personality is who I am & my attitude depends on who you are!");
        englist.add("Attitude is a little thing that makes a big difference.");
        englist.add("I don't care what people think or say about me!");
        englist.add("What people say to your face is not a problem. The problem is what they say behind your back.");
        englist.add("A bad attitude is plane tire if you not change it you can never think positive!.");
        englist.add("Please don't interrupt me while I'm ignoring you.");
        englist.add("I'm that ugly I asked myself out and I said no.");
        englist.add("People say me bad.....trust me i am the worst.");
        englist.add("Some people are just so FAKE that if you look properly at the back of their neck, you'll find a tag saying MADE IN CHINA");
        englist.add("I do not mind the crazy people, it's the normal one that freaks me out!");
        englist.add("I got a simple rule about everybody. If you don't treat me right.. shame on you!!");
        englist.add("I have no time to hate people... who hate me... because, I'm always busy in loving people, who love me.");
        englist.add("I am not perfect but I am limited Edition.");
        englist.add("Wonders why people keep doing the same old things, but yet expect a different outcome!!");
        englist.add("Excellence is not a skill. It is an attitude.");
        englist.add("The only disability in life is a bad attitude.");
        englist.add("If I agreed with you we'd both be wrong.");
        englist.add("I want my Girlfriend like Google, She will understand me better.");
        englist.add("The real reason women live longer than men because they don't have to live with women.");
        englist.add("Good news is I'm smiling. Bad news is it's the kind of smile that people should fear.");
        englist.add("Men also have FEELINGS, for example they can feel HUNGRY.");
        englist.add("Life without mistakes is like, education without books.");
        englist.add("You can't expect me to think before I speak. I was born without that ability. So I'm sorry if the truth hurts.");
        englist.add("Don't ask me for my opinion if you can't handle the truth. I'm not going to lie to make you feel better.");
        englist.add("I Wish My Parents Were Like Google... They Should Understand Me Even Before I Complete.");
        englist.add("Free your heart from any hatred. Free your mind from any worries. Live simply. Give more. Expect less.");
        englist.add("Always remember you are unique, just like everyone else.");
        englist.add("Your imagination has much to do with your life. It is for you to decide how you want your imagination to serve you.");
        englist.add("Every people is a intelligent, When he work Hard!");
        englist.add("If you want to make your dreams come true, the first thing you have to do is wake up.");
        englist.add("Attitude is like underwear Don't show it just wore it!");
        englist.add("People who have High And Unnecessary attitude, deserves the Standing Ovation of my Tallest Finger.");
        englist.add("In Love Story, Mom Agrees And Dad Disagrees? It's Because Mom Knows What Love Is... And Dad Knows What Boys Are.");
        englist.add("People say I have a dirty mind, But I say its just creative!");
        englist.add("Before you judge me make sure that you're perfect.");
        englist.add("I am not Spider man Nor Superman However i am superhero for my GF!");
        englist.add("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.");
        englist.add("I don't have time to hate people,who hate me.because, I'm too busy in loving people who love me.");
        englist.add("It is sad but truthful that some people simply grow old, but they never grow UP!");
        englist.add("I don't have dirty mind, I have s3xy imagination.");
        englist.add("My Attitude :- Don't mess wid me m too bad... Bcoz u cnt handle my goodness!!");
        englist.add("I don't insult people, I just describe them");
        englist.add("I don't come with dice. So don't play me.");
        englist.add("I hate when I'm about to HUG someone really s3xy and my face hits the mirror. :p");
        englist.add("If you think you are too small to make a difference, try sleeping in a closed room with a mosquito.");
        englist.add("I don't insult people, I just describe them.");
        englist.add("2 mints silent for those.. Who seen but didn't like my posts.");
        englist.add("AtTitUdE is the result on uR aCtiOn.. So, if eu doN't LyK mY aTtItUdE.. BLam uRsLf");
        englist.add("Good girls are bad girls that never get caught.");
        englist.add("I'm sorry I mistook all our laughs, long nights, sweet texts & inside jokes as you caring. I'll think twice before wasting my time again.");
        englist.add("Don't Play With Me ! Because I know I Can PLAY Better Than You.");
        englist.add("The greatest discovery of all time is that a person can change his future by merely changing his attitude.");
        englist.add("My alarm clock is clearly jealous of my amazing relationship with my BED.");
        englist.add("The only difference between success and failure is one's attitude.");
        englist.add("You say I have a bad attitude, guess what? My attitude is a result of your actions!! Change your actions and I will change my attitude : o )");
        englist.add("I wish I could record my dreams and watch them later.");
        englist.add("My Attitude is my born gift and nobody take from me.");
        englist.add("Silence is the best answer to a FOOL.");
        englist.add("People say me bad..but trust me I am the worst!");
        englist.add("Be yourself, who else is better qualified?");
        englist.add("Life is too short Don't waste it updating status!");
        englist.add("Intelligence can bring you to success. But it's your attitude that keeps you there. Remember Grades Don't Define A Person.. ATTITUDE DOES.");
        englist.add("Every problem comes with some solution.. If it doesn't have any solution, it's a Girl!");
        englist.add("You can help someone with low self-esteem, but is almost impossible to help someone with a negative attitude.");
        englist.add("I don't have time to hate people bcz.. I'm busy loving people who love me.");
        englist.add("I Refuse To Have A Battle Of Wits With An Unarmed Person.");
        englist.add("Single is not a status. It is a word that best describes a person who is strong enough to live and enjoy life without depending on others!!");
        englist.add("When someone says: you are UGLY TELL them oh sorry I was trying to look like you");
        englist.add("If you love someone set them free. If they come back, set them on fire. ;) :D");
        englist.add("I am single because God is busy writing the best love story for me…");
        englist.add("Not always 'Available' Try your Luck.");
        englist.add("Sometimes people a high five on the face with a CHAIR.");
        englist.add("My mind makes me a girl, my attitude a bitch and my class a lady J");
        englist.add("There comes a point in life, when you realize who really matters, who never did, and who always will.");
        englist.add("Our attitude towards others determines their attitude towards us.");
        englist.add("When you care about someone, their happiness matters more than yours!!");
        englist.add("I destroy my enemies when I make them my friends.");
        englist.add("Do your legs hurt from running through my dreams all night?");
        englist.add("Sometimes you have to just move forward, and move on. No doubts, no questions and no looking back... Just move on.");
        englist.add("Every problem comes with solution, but my GF don't have.");
        englist.add("If you think I am BAD than you're wrong, I am the worst.");
        englist.add("I hate when people look at my phone while I'm typing. It's not that I have something to hide... It's just none of their damn business :/");
        englist.add("An ugly personality destroy a pretty face.");
        englist.add("People with high ego and unnecessary attitude deserves the standing ovation of the tallest finger.");
        englist.add("Beauty is skin deep but attitude is to the bone.");
        englist.add("The meaning of things lies not in the things themselves, but in our attitude towards them");
        englist.add("People are like 'MuSic' some say the 'TrUth' and rest,just noise.");
        englist.add("Life is too short. Don't waste it reading my status.");
        englist.add("I do not exist to impress the world. I exist to live my life in a way that will make me happy.");
        englist.add("People say nothing's impossible, but I do nothing everyday");
        englist.add("We have enough gun control. What we need is idiot control.");
        englist.add("The best thing about being me, I'm a limited edition and there are no other copies!");
        englist.add("My opinions may have changed, but not the fact that I am right.");
        englist.add("Nothing positive comes from being negative all the time. Change your attitude!");
        englist.add("Never get into fights with ugly people, they have nothing to lose.");
        englist.add("I wish I had 'Google' in my mind and 'Antivirus' in my heart.");
        englist.add("I am not changed it's just I grew up and you should try too.");
        englist.add("If you want to cry, use a tissue... not your status...!! :D :P");
        englist.add("I know i am awesome, so i don't care about your opinion.");
        englist.add("I never prove to be good enough.. For every one...! But I'm the best for them who understand me. :)");
        englist.add("I hate when people look at my status and say 'Its Bakwas'.");
        englist.add("Being glamorous Is not a crime.");
        englist.add("I'm pretty sure the whole ladies first thing was created by a guy just to check out @ss.");
        englist.add("Attitudes are more important than facts.");
        englist.add("I AM WHAT I AM...your approval isn't needed and it wasn't never asked! Sorry");
        englist.add("I'm sorry my fault. I forgot you're an Idiot.");
        englist.add("Attitude is like wrist watch. Every watch shows different time than other and everyone thinks his watch is showing right time.");
        englist.add("I Wish My Parents Were Like Google.. They Should Understand Me Even Before I Complete.");
        englist.add("If people have a problem with you, always remember, it is THEIR problem.");
        englist.add("I am single because God is busy writing the best love story for me...Hey I found your nose, it was in my business again.");
        englist.add("I am multi talented, i can talk and piss you off at the same time.");
        englist.add("I expect to succeed at whatever I put my mind to.");
        englist.add("Smartness is a perfect beauty.");
        englist.add("WIFE & INSULT Are Somewhat Similar, They Always Look Good,IF IT IS NOT YOURS!");
        englist.add("Remember one thing, you might be a PLAYER. But i am the GAME.");
        englist.add("When Sum One Hates You for no reason.. Give them a reason.");
        englist.add("Whenever I think of quitting smoking, I need a cigarette to think.");
        englist.add("The task ahead of us is never as great as the power behind us.");
        englist.add("If people are trying to bring you 'Down'.. It only means that you are 'Above them'.");
        englist.add("Take charge of your attitude. Don't let someone else choose it for you.");
        englist.add("Taking revenge is wrong..very very wrong.. But very very fun.");
        englist.add("If you expect me to be there for you. You should be there for me too.");
        englist.add("Act like you are wearing invisible crown. That's 'Attitude'");
        englist.add("Never lose your sense of wonder.");
        englist.add("I don't have an attitude!! I have a personality you can't handle!!!");
        englist.add("Weakness of attitude becomes weakness of character. - Albert Einstein");
        englist.add("Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude. - Thomas Jefferson");
        englist.add("DP to lagalu par teri aukat nahin hai.");
        englist.add("Don't hate me, just get to know me first!");
        englist.add("I will win, not immediately but definitely.");
        englist.add("Alter your attitude and you can alter your life.");
        englist.add("'Dream' as if you'll live forever.. Live as if tomorrow is last one.");
        englist.add("You give me the kind of feeling people write novels about.");
        englist.add("Your looks don't make you Beautiful, it's the person inside who makes you beautiful.");
        englist.add("Attitude Matters : Don't Say, \"No One Likes Me..!! \" Just Say, \"There Is No One Like Me..!!When Someone Says");
        englist.add("If you can;t convince them, confuse them.");
        englist.add("Some people just need a High-Five.. On the face.");
        englist.add("Always stay true to yourself & never sacrifice who are you for anyone.");
        englist.add("Do not give advise unless you are asked to.");
        englist.add("When people judge you on what they are told or what they see.. Get too know me first.");
        englist.add("Be a girl with a mind, a bitch with an attitude, and a lady with class.");
        englist.add("Why waste your time caring for people who don't even acknowledge your existence? Huh");
        englist.add("I am not a King but I am a King Maker.");
        englist.add("I can't change the destination of wind but I can change the bad thinking of mine.");
        englist.add("Style is a reflection of your attitude and personality.");
        englist.add("I tried being like you, my personality didn't like it.");
        englist.add("Someone asked me How is your life? I just smiled and replied, She is fine.");
        englist.add("Nothing great was ever achieved without enthusiasm.");
        englist.add("WIFE & INSULT Are Somewhat Similar, They Always Look Good, IF IT IS NOT YOURS!.");
        englist.add("If you obey all the rules, you'll miss all the fun.");
        englist.add("A positive attitude can really make dreams come true grin emoticon - it did for me.");
        englist.add("They can because they think they can.");
        englist.add("There are two type of people winner and Losser, Winner always Working Hard, Losser Always try to shortcut for win.");
        englist.add("If you are good at something, never do it for free :D");
        englist.add("I hate when people look at my phone while I'm typing. It's not that I have something to hide... It's just none of their damn business");
        englist.add("'B+' is not my blood group, neither my grade in maths. Its my favourite Quote: BE POSITIVE");
        englist.add("I am not Spiderman Nor Superman However i am superhero for my GF!");
        englist.add("There is no market for your emotions, So never advertise your feelings, just display your attitude.");
        englist.add("When i was born, i was so surprised, I didn't talk for a year and half.");
        englist.add("The ideal attitude is to be physically loose and mentally tight.");
        englist.add("Only difference between Good day and a Bad day is your Attitude..");
        englist.add("Those who know love has also the risk of knowing pain.");
        englist.add("Try to solve your problem yourself... Don't Depend on other!");
        englist.add("Stop checking my Status, Go and love your GF");
        englist.add("Sometimes you need to maintain a distance to keep them close to you.");
        englist.add("Smile in front of people who hate you... Ur happiness kills them..");
        englist.add("Always trying to cool my self");
        englist.add("I don't have an Attitude.... just a Personality that you can't handle it.");
        englist.add("People will love you. People will hate you. Others will secretly wish to be you.");
        englist.add("I asked God for a bike, but I know God doesn't work that way. So I stole a bike and asked for forgiveness.");
        englist.add("I may be fat, but you're ugly - I can lose weight!");
        englist.add("When I read about the evils of drinking, I gave up reading.");
        englist.add("Good thing is listening a new song is that it doesn't remind you of anyone.");
        englist.add("Good Girl are those which can help people, Bad Girl have no time to help.");
        englist.add("Your attitude determines your direction.");
        englist.add("When Sum One Hates You for no reason.... Give them a reason :P :D");
        englist.add("Those who like me... Raise your hands.. And those who don't like me raise your Standards.");
        englist.add("My attitude is a result of your actions.. So if you don't like my attitude blame yourself.");
        englist.add("I'm cool but Summer made me hot!");
        englist.add("I enjoy when people show ATTITUDE to me because it shows that they need an ATTITUDE to impress ME.");
        englist.add("I don't have an attitude problem. You have a perception problem");
        englist.add("My attitude based on how you treat me.");
        englist.add("Awesome ends with ME and Ugly starts with you.");
        englist.add("Don't PLAY with Me ! Coz i know I Can PLAY Better Than You.");
        englist.add("Always smiling, because your smile is a reason for many others to smile.. Smile please!!");
        englist.add("Weakness of attitude become weakness you!");
        englist.add("Being silent is my Attitude.");
        englist.add("Patience is not a virtue. Its just a waste of Time! :P");
        englist.add("Two fundamentals of cool life - Walk like you are the king Or walk like you don't care, who is the king.");
        englist.add("90% of the time I say 'BRB' it just means I don't want to talk to you anymore.");
        englist.add("I have a new theory in life...what other people think of me is truly none of my business!");
        englist.add("I miss the days when I was put my head on my desk.");
        englist.add("Galileo-Great mind! Einstein-genius mind! Newton-Extraordinary mind! Bill gates-brilliant mind.. ME-Never Mind!");
        englist.add("I was reminded that my blood type is Be Positive.");
        englist.add("Beauty in the skin & Attitude in the bone!");
        englist.add("I never insult people I only tell them what they are.");
        englist.add("If loving you is wrong, Then i don't want to be right.");
        englist.add("Me.....myself...and I..!!");
        englist.add("My door is always open so feel free to leave.");
        englist.add("I taught your boyfriend that little thing you like.");
        englist.add("Work until you don't have to, introduce yourself.");
        englist.add("Dear Lord, there is a bug in your software... it's called #Sunday, please fix it !");
        englist.add("Style is a way to say who you are without speaking.");
        englist.add("I don't insult people , I just describe them");
        englist.add("You are today where your thoughts have brought you, you will be tomorrow where your thoughts take you.");
        englist.add("Hey I found your nose, it was in my business again.");
        englist.add("Be the Best Version of yourself.");
        englist.add("I Am Not Special, I Am Just Limited Edition :P");
        englist.add("I'm not going to feel sorry for myself anymore. If you were stupid enough to walk away, I'll be smart enough to let you go.");
        englist.add("For success, attitude is as much important as ability.");
        englist.add("hate me? don't care? love me? love you too?think I'm a bitchy? f*ck off?");
        englist.add("Your attitude, not your aptitude, will determine your altitude.");
        englist.add("Don't walk as if you rule the world...Walk as if you don't care who the hell rules the world.");
        englist.add("When we can't laugh again and again on the same joke. There's no point crying again and again for the same pain.");
        englist.add("The ones who are crazy enough to think that they can change the world are the ones who do.");
        englist.add("They say don't drink and drive. Well.. yesterday I was drinking a juice box while riding my tricycle. Yeah. I'm a bad@ss.");
        englist.add("I am single as my love story is being written by god and he is busy is making it best.");
        englist.add("Laugh at your problems, everybody else does.");
        englist.add("I have attitude for those who force me to show them :D");
        englist.add("I am who i am today because of the choice i made yesterday.");
        englist.add("Don't See My Status, Appointment is needed.");
        englist.add("Adopting the right attitude can convert a negative stress into a positive one.");
        englist.add("I Was Born Cool, Global Warming Made Me Hot.");
        englist.add("I am who i am, you approval is not needed.");
        englist.add("Stop checking my status ! Go Get A Life :P");
        englist.add("Don't get confused between my personality and my attitude. My personality is WHO I AM and my attitude depends on WHO YOU ARE.");
        englist.add("I don't have a bad handwriting, I have my own FONT.");
        englist.add("My words are like a china phone. They have no guarantee!");
        englist.add("If i liked your status on facebook that means you have entertained me.");
        englist.add("If people have a problem with you then ask him her problem!");
        englist.add("If you hate me – Log on to KISS-MY-ASS.com");
        englist.add("I will win not immediately, but Definitely.");

        if (isNetworkConnected()) {
            englishlists.setVisibility(View.VISIBLE);
            Net_connection.setVisibility(View.GONE);

        } else {
            englishlists.setVisibility(View.GONE);
            Net_connection.setVisibility(View.VISIBLE);
        }

        rjptadapter = new Shayri_Adapt(getActivity(), englist, "rjpthindi");
        englishlists.setAdapter(rjptadapter);

        return view;
    }

    private boolean isNetworkConnected() {
        ConnectivityManager cm = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);
        return cm.getActiveNetworkInfo() != null && cm.getActiveNetworkInfo().isConnected();
    }

}