package ind.apptech.captionsforinstagram.fragment;

import android.content.Context;
import android.net.ConnectivityManager;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.RecyclerView;
import androidx.recyclerview.widget.StaggeredGridLayoutManager;

import ind.apptech.captionsforinstagram.Shayri_Adapt;
import com.apptech.captionsforinstagram.R;

import java.util.ArrayList;

public class Crazy extends Fragment {

    RecyclerView rajputlist;
    private RecyclerView.LayoutManager layoutManager;
    Shayri_Adapt rjptadapter;
    ArrayList<String> englist = new ArrayList<>();
    LinearLayout Net_connection;

    public Crazy() {
        // Required empty public constructor
    }

    public static Crazy newInstance(String param1, String param2) {
        Crazy fragment = new Crazy();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.hindi_shayri, container, false);

        rajputlist = (RecyclerView) view.findViewById(R.id.English_list);
        Net_connection = view.findViewById(R.id.Net_connection);
        layoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.VERTICAL);
        rajputlist.setLayoutManager(layoutManager);
        englist = new ArrayList<>();


        englist.add("Dear Google, Please stop behaving like a GIRL. Will u please allow me to complete the whole sentence before you start guessing & suggesting.");
        englist.add("I wish my bank account refilled as fast as my laundry basket.");
        englist.add("Why do I fall in love with people who are all ready taken or have feelings for someone else?");
        englist.add("I don’t go looking for trouble. Trouble usually finds me.");
        englist.add("God was showing off when He created you.");
        englist.add("What do girls want? EVERYTHING!!!");
        englist.add("Today's Relationships: You can touch each other but not each others phones.");
        englist.add("For all the girls that say ..... All guys are the same ...... Who told you to try them ALL.");
        englist.add("If life gives you questions, Google gives you answers.");
        englist.add("Parachute for sale, used once, never opened!!");
        englist.add("Be thankful for all you have, because you never know what will happen next.");
        englist.add("I hate people who steal my ideas, before I think of them :)");
        englist.add("A man asks a trainer in the gym: I want 2 impress that beautiful girl , which machine can I use? Trainer replies: Use the ATM");
        englist.add("Most emotional moment in a boys life, When a girl says, Can you give me your number :D");
        englist.add("Life is Short – Chat Fast!");
        englist.add("Behind every successful man... There is a confused woman.");
        englist.add("I'm not short, I am just concentrated awesome!");
        englist.add("You can stay in my heart without paying single penny.");
        englist.add("Person you love is 72.8% water.");
        englist.add("I live in a world of fantasy, so keep your reality away from me!");
        englist.add("If my love for you is a crime, I want to be the most wanted criminal.");
        englist.add("Dear Lord, all I ask for a chance to prove that winning the lottery won't make a bad person.");
        englist.add("Faces YOU Make ON The Toilet lol (o_o) (>_<) (0_0) (^_^)");
        englist.add("Boys will be boys as long as there are no girls in the picture.");
        englist.add("I love my job only when I'm on vacation");
        englist.add("I had a wonderful childhood, which is tough because it's hard to adjust to a miserable adulthood. – Larry David");
        englist.add("If you stop telling lies about me, I’ll stop telling the truth about you.");
        englist.add("The question I have not been able to answer is What... does a woman want?");
        englist.add("Excuse me! Ye lijiye aapki soch. Mujhe giri hui mili thi. :P");
        englist.add("Love is not having someone give you the world. Love is creating a whole new world together. Happy Valentines Day");
        englist.add("How can i miss something i never had?");
        englist.add("God is really creative, I mean.. just look at me! :)");
        englist.add("People say nothing is impossible, but I do nothing every day.");
        englist.add("I don't usually sleep enough, but when I do, it's still not enough ;)");
        englist.add("Don't worry. God is always on time.");
        englist.add("Boys think of girls like books, if the cover doesn't catch their eyes, they won't even bother to read what's inside.");
        englist.add("I smile and act like nothing is wrong, its called putting shit aside and being strong.");
        englist.add("Do you ever look at your friends and think “why the hell aren’t we comedians?”");
        englist.add("Failure is not an option — it comes bundled with Windows.");
        englist.add("Sorry about those texts I sent you last night, my phone was drunk.");
        englist.add("My phone is like my lover. Its the last thing I see at night, and the first thing I wake up to every morning.");
        englist.add("My family says I talk in my sleep but nobody at work has ever mentioned it. lolz");
        englist.add("When I'm on my death bed, I want my final words to be I left one million dollars in the.");
        englist.add("If you don't care stop talking about it.");
        englist.add("God is really creative , i mean ..just look at me :P");
        englist.add("Having a best friend with the same mental disorder is a blessing. LOL");
        englist.add("Just finished deleting some friends on Facebook, if you can read this then you got lucky.");
        englist.add("If you love someone, set them free. If they come back, nobody else wanted them either :)");
        englist.add("Girls use photoshop to look beautiful.. Boys use photoshop to show their creativity.");
        englist.add("Strive not to be a success, but rather to be of value.");
        englist.add("Don't kiss behind the garden, Love is blind but the neighbours are not.");
        englist.add("Quit your job, buy a ticket, get a train, fall in love and never return.");
        englist.add("Never make eye contact while eating a banana.");
        englist.add("Girl, you better have a license, cuz you are driving me crazy!");
        englist.add("The stuff you heard about me is a lie, I’m way worse…");
        englist.add("I am not addicted to WHATS APP. I only use it when I have time ....... lunch time, break time, bed time, this time, that time, any time, all the time. :)");
        englist.add("I really need 5 hours of Facebook to balance out my 5 minutes of studying.");
        englist.add("Wrestling is obviously fake. Why would two people fight over a belt when neither of them are wearing pants?");
        englist.add("Freedom of speech is lost when you get into a relationship and she is beautiful.");
        englist.add("I have not failed. I’ve just found 10,000 ways that won’t work.");
        englist.add("Being stupid is its own reward.");
        englist.add("A wise man once said, You can’t be old & wise, if you were never young & crazy.");
        englist.add("I think I got a fever, a fever of you :)");
        englist.add("I used to have an open mind but my brains kept falling out!!!");
        englist.add("Years of education, solving tough problems, handling complex issues, yet we take a while standing before glass doors thinking whether to Push or Pull.");
        englist.add("I used to think I was indecisive, but now I'm not too sure.");
        englist.add("In my house I'm the boss, my wife is just the decision maker.");
        englist.add("Newton's law of love: Love can neither be created nor be destroyed. Only it can transfer from one girlfriend to another with some loss of money.");
        englist.add("My back is not a voicemail, say it to my face.");
        englist.add("Don't kiss behind the garden, Love is blind but the neighbors are not.");
        englist.add("It is a sad fact that 20% of marriages in this country end in divorce. But hey, the remaining end in death. You could be one of the lucky ones.");
        englist.add("Flirtationship: More than a friendship and less than a relationship.");
        englist.add("If a thoughtless thought is thought, would a thought thoughtlessly think of thoughtless thoughts whenever thinking thoughts are thoughtless? What a thought, eh?");
        englist.add("Wonders if its bad when I’m talking to myself and I’m not even listening…");
        englist.add("One day your prince will come. Mine just took a wrong turn, got lost and is too stubborn to ask for directions :)");
        englist.add("Money can't buy happiness, but it pays for internet, which is pretty much the same thing.");
        englist.add("Seeing a spider is nothing. It becomes a problem when it disappears.");
        englist.add("I have enough money to last me the rest of my life, unless I buy something.");
        englist.add("When a bird hits your window have you ever wondered if God is playing angry birds with you?");
        englist.add("I gotta go to work today because millions of people on welfare depend on me.");
        englist.add("We become what we think about.");
        englist.add("You don’t have to be crazy to hang out with me. I’ll train you. Make your appointment today.");
        englist.add("Friends are forever, until they get in a relationship!! :P");
        englist.add("Life isn't about getting and having, it's about giving and being.");
        englist.add("Never make the same mistake twice, there are so many new ones, try a different one each day.");
        englist.add("You must be a certified helmet wearing window licker to ride the sunshine bus..");
        englist.add("How come wrong numbers are never busy?");
        englist.add("OH MY GOD, The rain’s wet..");
        englist.add("I came here in peace, seeking gold and slaves. – Jack Handey");
        englist.add("Shhhhhhhh everyone around me is in a relationship and I am just here with my laptop & this page.");
        englist.add("A husband is someone who, after taking the trash out, gives the impression he just cleaned the whole house.");
        englist.add("There's no such thing as addiction, there's only things that you enjoy doing more than life. – Doug Stanhope");
        englist.add("My head is telling my heart “I told you so!”.");
        englist.add("Everything is 10x funnier when you are not supposed to laugh.");
        englist.add("I took an IQ test and the results were negative.");
        englist.add("Laziness Is The Mother Of All Bad Habits But Ultimately She Is A Mother And We Should Respect Her.");
        englist.add("I was born to be a pessimist. My blood type is B Negative. :p");
        englist.add("Admit it, you listen to other strangers conversations and mentally give your opinion.");
        englist.add("I can handle pain until it hurts.");
        englist.add("I cannot tell you how grateful I am, I am filled with humidity.");
        englist.add("For you men who think a woman's place is in the kitchen, remember thats where the knives are kept. :)");
        englist.add("Boys think of girls just ike books; if the cover doesn’t catch their eye, they won’t bother to read what’s inside.");
        englist.add("I hate when I am about to hug someone really s3xy and my face hits the mirror.");
        englist.add("Marriage is like going to a restaurant and order your choice from the menu, And then look at neighbouring table n wish you ordered that.");
        englist.add("Relationships would be easier if people came with a CLEAR HISTORY button.");
        englist.add("I'm not lazy, I'm on energy saving mode.");
        englist.add("Gravity always gets me down. :)");
        englist.add("After getting drunk, Bachelor of Technology turns into Master of Philosophy.");
        englist.add("You can never really say what's on your mind, when your family is on Facebook.");
        englist.add("The most powerful words other than I LOVE YOU is Salary is Credited :)");
        englist.add("If school has taught us anything, it's texting without looking :)");
        englist.add("I swear my pillow could be a hairstylist I always wake up with the weirdest hairdos. :D");
        englist.add("What i if told you...you the read first line wrong... same with the second... :p");
        englist.add("My family says I talk in my sleep but nobody at work has ever mentioned it. lol");
        englist.add("I always learn from mistake of others who take my advice :)");
        englist.add("Only fools fall in love and I guess I'm one of them :)");
        englist.add("When I see you, I miss your smile. When I see your smile, I miss your hug. When you hug me, I want your kiss …… Oh I’m just so crazy about you.");
        englist.add("Its Cute When your Crush's Crush is You.");
        englist.add("Dear mom and dad, when I lie to you, it's for your own good. :P");
        englist.add("Girls are like parking spaces, all the good ones are already taken.");
        englist.add("Press “like” if you are crazy.");
        englist.add("Its crazy how much you let someone hurt you without realizing it.");
        englist.add("At least mosquito's are attracted to me.");
        englist.add("Girls work on their looks but not their minds b'coz they know boys are stupid, not blind.");
        englist.add("If life gives you lemons, just add vodka.");
        englist.add("I want some one to give me a Loan and then leave me Alone. :)");
        englist.add("I know the door to your heart belongs to another, but I think I can slip in through the window.");
        englist.add("GOOGLE must be a woman because it knows everything.");
        englist.add("Every time I drink I get awesome :-)");
        englist.add("Excuse me, do you mind if I stare at you for a minute? I want to remember your face for my dreams.");
        englist.add("Thanks to Google, Wikipedia, and whoever the hell invented copy and paste. Thank you Guys.");
        englist.add("The awkward moment when you enter class late and everyone stares at you.");
        englist.add("I'm a Teenager: I have a messy room. I spend most of my time online. I have private shit on my phone. I go to bed late do whatever the fuck I like and I'm crazy about 1 person.");
        englist.add("The human brain is amazing. It functions 24 hours a day from the time we were born, and only stops when we take exam or are in love.");
        englist.add("I speak two languages, Body and English.");
        englist.add("They don’t know that we know they know we know.");
        englist.add("You can fool some of the people all the time, and those are the ones you want to concentrate on.");
        englist.add("Aging is inevitable, Maturing is optional.");
        englist.add("Don’t think too much, you’ll create a problem that wasn’t even there in the first place.");
        englist.add("How is a poor man a lot like a rich man? They both have an iPhone.");
        englist.add("I’m not crazy, I’m just special.");
        englist.add("I’ve been thinking. I know, it scares me too..");
        englist.add("Being someones FIRST may be great but being LAST is perfect…");
        englist.add("It's funny how people judge other's mistakes while they also do the same thing.");
        englist.add("Onions make me sad. A lot of people don't realize that. – Mitch Hedberg");
        englist.add("If you don't succeed at first, hide all evidence that you tried.");
        englist.add("I don't believe that love comes to those who wait. Today love comes to those who flirt. LOLz");
        englist.add("She loves me or not but I love her a lot. :P");
        englist.add("Am i the only one who gets this random urge to help old ladies half way across the street and leave them there?");
        englist.add("I hate how chocolates immediately melt on my fingers. I mean, am i that hot?");
        englist.add("Dear Food, Either stop being so delicious or stop making me fat :)");
        englist.add("Try to say the letter M without your lips touching.");
        englist.add("In Modern Politics, Even The Leader Of The Free World Needs Help From The Sultan Of Facebookistan!");
        englist.add("Sometimes its better to bunk the class instead of attending it Cause today wen I look back, my marks never make me laugh but memories d...");
        englist.add("Accept the craziness. Life will be a bore without it.");
        englist.add("I wonder what happens when doctor's wife eats an apple a day. :)");
        englist.add("Babies are so lucky. They can sleep all day still everyone loves them.");
        englist.add("I hate when ex’s say… “I am here if you need me.” like….? where were you? when we were together & I needed you?");
        englist.add("I don’t care if you think I’m crazy. Life is too short to be normal.");
        englist.add("80% of boys have girlfriends.. Rest 20% are having brain.");
        englist.add("Im a humble person, really. I'm actually much greater than I think I am.");
        englist.add("Arrange marriage these days is the agreement between two broken hearts.");
        englist.add("Running away does not help you with your problems, unless you are fat.");
        englist.add("We all have that one person we hate but constantly look at their facebook profile.");
        englist.add("TODAY has been cancelled. Go back to BED :)");
        englist.add("When a newly married man looks happy, we know why. But when a ten-year married man looks happy, we wonder why.");
        englist.add("I'm a good boy with bad habits :P");
        englist.add("I really want to work so hard. But being lazy is so much fun.");
        englist.add("If Your age was to be determined by the 2 last digits of your phone number, how old wil you be?");
        englist.add("I want someone to look at me the way I look at cupcakes!!");
        englist.add("Some people should have multiple Facebook accounts to go along with their multiple personalities.");
        englist.add("Did anyone else notice the sound if you click the like button on my status?");
        englist.add("Its better to fail than to cheat but its better to cheat than to repeat.");
        englist.add("Laugh alone and the world thinks you're an idiot.");
        englist.add("We are WTF generation .... WhatsApp, Twitter and Facebook :D");
        englist.add("Nothing is illegal until you get caught :)");
        englist.add("Behind every successful man is a surprised woman.");
        englist.add("Dear Google, thank you for doing most of my homework for me. :)");
        englist.add("I know that you know that I know what you know and you know what they know so I know what you know they know, you know?");
        englist.add("I Like to study.. Arithmetic - NO ... world history - NO .... chemistry - NO .... GIRLS - YES!");
        englist.add("We live in WTF generation - Wikipedia, twitter, facebook");
        englist.add("I was talking to myself last night and we both agreed that you’re crazy..");
        englist.add("Money is made of paper, paper is made of wood, and wood is made from trees. Therefore, money does grow on trees.");
        englist.add("Sometimes I wonder how many miles I have scrolled my mouse wheel.");
        englist.add("Every woman should have four pets in her life. A mink in her closet, a jaguar in her garage, a tiger in her bed, and a jackass who pays for everything.");
        englist.add("Do not keep all your work for tomorrow, always remember you can also do it the day after tomorrow.. Be lazy, Think crazy");
        englist.add("People never remember the million times you help them, only the one time you don’t.");
        englist.add("I’m shy at first, but once I’m comfortable with you get ready for some crazy shit.");
        englist.add("Some people should try thinking, it’s not illegal yet");
        englist.add("You remind me of my Chinese friend... Ug Lee");
        englist.add("Flip a coin... If head comes, I am yours, if tail comes then you are mine. :)");
        englist.add("Are you going to kiss me or do I have to lie to my diary? :)");
        englist.add("Hee Hee Hee Hee Hee, you can’t stop me! I broke my off switch..");
        englist.add("It doesn’t matter what people say about you. It matters what you’re going to do to them after they say it!");
        englist.add("I only need 3 things in life: Food, Wifi, Sleep :)");
        englist.add("My biggest concern in life is actually how my online friends can be informed of my death!");
        englist.add("Every girl deserves ONE GUY who looks at her every day like it's the first time he saw her. And Im that ONE GUY :)");
        englist.add("Dear Lord, there is a bug in your software...it's called #Monday, please fix it");
        englist.add("I wish I could record my dreams and watch them later.");
        englist.add("I'm Jealous Of My Parents... I'll Never Have A Kid As Cool As Theirs!");
        englist.add("All men are born free and equal. If they go and get married, that’s their own fault.");
        englist.add("I am not addicted to Facebook. I only use it when I have time ... ... ... lunch time, break time, bed time, this time, that time, any time, all the time. :)");
        englist.add("When I joke they take it seriously. When I am serious they take it as a joke.");
        englist.add("If you want to read about love and marriage, you have to buy two separate books.");
        englist.add("Who needs television when there is so much drama on Facebook.");
        englist.add("I have a problem. My proble is love and ……… My solution is you.");
        englist.add("The strawberry shampoo doesn’t taste as good as it smells.");
        englist.add("If you can't convince them, Confuse them.");
        englist.add("Does anyone else get scared when a text reads “Can I ask you a question?”");
        englist.add("That awkward moment when you wait for a text but you realize you are the one that didn’t reply.");
        englist.add("The only thing I gained so far in THIS YEAR is weight :)");
        englist.add("Every boy wants a good girl to be bad just for him and every girl wants a bad boy to be good just for her. Crazy World");
        englist.add("Your lips look so lonely. Would they like to meet mine?");
        englist.add("Excuse me .... Please empty your pockets .... I think you stole my heart.");
        englist.add("When I am home alone, every noise I hear is a serial killer.");
        englist.add("People who exercise live longer, but what's the point when those extra years are spent at gym.");
        englist.add("Save water drink beer.");
        englist.add("A girl jogging in the park helps atleast 5 boys to be fit and in shape.");
        englist.add("How do people write an auto biography? I can barley remember what I had for lunch yesterday :)");
        englist.add("One should always be in love. That is the reason one should never marry.");
        englist.add("There are three sides to an argument – your side, my side and the right side.");
        englist.add("Definition of human being: a creature that cuts trees, makes paper & write SAVE TREES on the same paper.");
        englist.add("Decided to burn lots of calories today so I set a fat kid on fire.");
        englist.add("Restaurant Advertisement: We serve food as HOT as your neighbour's wife; And beer as COLD as your own. :)");
        englist.add("People call me mike .. You can call me tonight.. :p");
        englist.add("Nothing is over until you stop trying.");
        englist.add("It's been 70+ years, Tom. You're never going to eat Jerry :)");
        englist.add("I love my six pack so much, I protect it with a layer of fat :)");
        englist.add("If you can't find the key to success, pick the lock.");
        englist.add("I'm on a whiskey diet.. I've lost three days already. – Tommy Cooper");
        englist.add("God made coke. God made pepsi. God made me. Oh so s3xy. God made rivers. God made lakes. God made you. Well... we all make mistakes.");
        englist.add("BRB = I don't want to talk to you. LOL = I have nothing else to say. Cool = I don't care.");
        englist.add("Dear MATH, stop asking to find your X, she's not coming back.");
        englist.add("Why does it always rain the hardest on those who deserve the sun?");
        englist.add("If you are going to speak bad things about me on my back, come to me. I'll tell you more.");
        englist.add("Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover.");
        englist.add("Being in a relationship is a full-time job; don’t apply if you’re not ready to commit.");
        englist.add("The two most common elements in the world are hydrogen and stupidity.");
        englist.add("Everything funnier when your supposed to be quiet..");
        englist.add("When I get a text from you, I immediately stop whatever I’m doing to read it.");
        englist.add("I am so cool, my selfie is called a kulfi!");
        englist.add("If you were to die tomorrow would you be happy with today?");
        englist.add("Dear LOL and Hamm, Thanks for being there when I have nothing else to say. :D");
        englist.add("Please GOD if you can't make me slim, make my friends fat.");
        englist.add("My wife dresses to kill. She cooks the same way.");
        englist.add("Last seen 1980! :D");
        englist.add("Girls are funny creatures. They hate it when you ask their age but will kill you if you forget their birthday.");
        englist.add("People say nothing’s impossible, but I do nothing everyday.");
        englist.add("Love never dies…only the lover changes. :P");
        englist.add("Silence is the best answer of all questions and Smile is the best reaction in all situations. Unfortunately both never help in VIVA & INTERVIEW.");
        englist.add("Fact: Phone on silent mode- 10 Missed call... Turns volume to loud- Nobody calls all day!!");
        englist.add("If Harry Potter is so magical then why can’t he fix his eye sight?");
        englist.add("My father always told me, 'Find a job you love and you'll never have to work a day in your life.");
        englist.add("Kiss me and you will see how important I am.");
        englist.add("I’m batter than you Ex and better then your NEXT!");
        englist.add("My study period = 15 minutes. My break time = 3 hours.");
        englist.add("Totally available!! Please disturb me!!");
        englist.add("C.L.A.S.S- come late and start sleeping :)");
        englist.add("I always give 100% at work: 13% Monday, 22% Tuesday, 26% Wednesday, 35% Thursday, 4% Friday :)");
        englist.add("Today morning when I was driving my Ferrari, the alarm woke me up. :D");
        englist.add("Some people have relationships and some people have patiyala.");
        englist.add("Milk does the body good but DAMN how much did you drink?");
        englist.add("My name is I. My problem is love. My solution is you.");
        englist.add("Warning, do you think its right time to talk to me?");
        englist.add("Marriage is just a fancy word for adopting an overgrown male child who can not be handled by his parents anymore.");
        englist.add("Cell phones these days keep getting thinner and smarter... people the opposite.");
        englist.add("If there is a WILL, there are 500 relatives.");
        englist.add("If you wish to avoid seeing a fool, you must break your mirror :D");
        englist.add("I wake up when I cant hold my pee in any longer.");
        englist.add("If a single teacher can't teach all the subjects then how could you expect a single student to learn all subjects.");
        englist.add("At least I can still smoke in my car.");
        englist.add("Always wear cute pajamas to bed you'll never know who you will meet in your dreams.");
        englist.add("I'll be drunk when I wake up, on the right side of the wrong bed.");
        englist.add("HEY YOU, yeah I'm talking to you, why the hell are you reading my status?");
        englist.add("Money can't buy LOVE but can buy WOMAN to make LOVE");
        englist.add("When I eventually met Mr. Right I had no idea that his first name was Always!");
        englist.add("The definition of a beautiful girl is one who loves me :)");
        englist.add("I don’t talk to myself, i talk to the little voices in my head that tell me to do evil cruel things to people and that’s the reason why i smile all the time..");
        englist.add("Quiet people have the loudest minds.");
        englist.add("I speak my mind. I never mind what I speak.");
        englist.add("Being single doesn’t mean you don’t know anything about love, it just means you know enough to wait for it.");
        englist.add("If I drink alcohol, I am an alcoholic. But if I drink fanta than . . . . . . I am fantastic!");
        englist.add("Hey there whatsapp is using me.");
        englist.add("Checking your symptoms on Google and accepting that fact that you're going to die.");
        englist.add("When people don't laugh at my jokes I just assume that they're not up to my level of comedy.");
        englist.add("Life is too short smile while you still have teeth.");
        englist.add("6 Peg Loading .. :D");
        englist.add("If Sunny Leone marries Sunny Deol, she will also become Sunny Deol :P :D :P :D");
        englist.add("Touch it gently, put two fingers inside, if it's wide use three fingers, make sure it's wet and rub up and down. Yep that's how you wash a cup.");
        englist.add("Love is 1 drink and 2 straws. Marriage is Don't you think you've had enough!");
        englist.add("I always dream of being a millionaire like my uncle!... He's dreaming too.");
        englist.add("I've had a horribly busy day converting oxygen into carbon dioxide. :)");
        englist.add("If College has taught us anything, it's texting without looking :)");
        englist.add("I don't worry about terrorism. I was married for two years. – Sam Kinison");
        englist.add("I used to like my neighbors, until they put a password on their Wi-Fi :)");
        englist.add("A bank is a place that will lend you money, if you can prove that you don't need it.");
        englist.add("Laughing at your own texts before you send them because you are so damn funny.");
        englist.add("It's not that I'm afraid to die, I just don't want to be there when it happens. – Woody Allen");
        englist.add("A lot of men & women would rather stay single b’coz they are tired of giving their everything and ending up with nothing.");
        englist.add("Why do they call it rush hour when nothing moves?");
        englist.add("Phones are better than girlfriends, At least we can switch off.");
        englist.add("People change, things change, time changes, priorities change, but expectations always remain the same..");
        englist.add("You can never buy Love....But still you have to pay for it ..");
        englist.add("my attitude depends upon the people in front of me");
        englist.add("If you were a tear in my eyes, I would not cry for the fear of losing you.");
        englist.add("If Da Vinci Code has been written by Punjabi author then its name would be Vinci Da Code");
        englist.add("Caution, Blind Man Driving.");
        englist.add("Here my dad comes on whatsapp... From now on my status would be '***no status***' or just a smiley.");
        englist.add("You want to come into my life, the door is open. You want to leave my life, the door is open. Just one request; don’t stand in front of the door, you are blocking traffic :)");
        englist.add("Be careful of following the masses - remove the m and who exactly are you following?");
        englist.add("When you see my head tilt to the side and I start to stare into space. I would run. The voices inside my head just gave me a brilliant idea. Be very afraid!");
        englist.add("Never argue with a fool. People might not know the difference.");
        englist.add("You people are crazy! I know…I can recognize my kind.");
        englist.add("I love my job only when I'm on vacation.");
        englist.add("Nothing moves faster than a girl untagging herself from an ugly picture :)");
        englist.add("My bed is always extra comfortable when I need to get out of it in the morning.");
        englist.add("There's like 7 billion people in this world and no one wants to date me. I hate this world ... huh");
        englist.add("Whatever it is — I didn't do it!");
        englist.add("Whoever says Good Morning on Monday's deserves to get slapped :)");
        englist.add("Girl, you better have a license, coz you are driving me crazy!");
        englist.add("If a book about failures doesn't sell, is it a success?");
        englist.add("If a man whistles at you, don't turn around. You are a lady not a dog");
        englist.add("If you love something, let it go. If it comes back, it was meant to be. If it does not, hunt it down & kill it.");
        englist.add("The best feeling in the world is when someone you hate tells a joke and nobody laughs :)");
        englist.add("I am 99.9% sure he doesnt like me. But its the 00.1% that keeps me going.");
        englist.add("Don’t call me crazy. I much prefer the term “mentally hilarious”.");
        englist.add("Our generation doesn't ring the doorbell...we text or call to say we're outside...");
        englist.add("I hate when people all of a sudden decide to be funny when I am drinking something :)");
        englist.add("If time does not wait for you, don't worry. Just remove the battery from the clock and enjoy life.");
        englist.add("That awkward moment when you are watching a movie with your dad and a love scene comes on.");
        englist.add("i haven’t lost my brain it just couldn’t handle my ideas so it left");
        englist.add("I am sure I have a defective iPhone, I keep pressing the home button and I'm still at work.");
        englist.add("Life is Short - Chat Fast!");
        englist.add("Boys, if you don't look like calvin klein models, don't expect us to look like victoria secrets angels. (From All Bachelor Girls Association) :)");
        englist.add("Nothing in the world is more common than unsuccessful people with talent.");
        englist.add("When a woman says WHAT? Its not because she didn't hear you. She's giving you a chance to change what you said.");
        englist.add("Everything I like is either Illegal, Immoral, Fattening, Addictive, Expensive, or Impossible.");
        englist.add("All my life I thought air is free until I bought a bag of chips.");
        englist.add("Is there anything more awkward than when you are singing along to a song on youtube and the music stops loading.");
        englist.add("I say no to drugs, but they don’t listen.");
        englist.add("I follow the quote, Always be true to yourself because I only lie to others... :P :D");
        englist.add("I'd like to thank the internet, Google, Wikipedia, Microsoft Word, and Copy & Paste :)");
        englist.add("I have a lot of growing up to do. I realized that the other day inside my fort. – Zach Galifianakis");
        englist.add("Don’t you sometimes just wish something would happen? Good or Bad; just for the sake of something happening.");
        englist.add("If life doesn't scare the shit out of you, you're doing it wrong.");
        englist.add("No I didnt trip The floor looked like it needed a hug.");
        englist.add("I hate fake people. You know what I'm talking about. Mannequins. :D");
        englist.add("Mosquitoes are like family. Annoying but they carry your blood.");
        englist.add("The first five days after the weekend are always the toughest.");
        englist.add("Bitch is just a term used for girl who refuses dog's proposal. :P");
        englist.add("Diet rule #1: If nobody sees you eating it, it doesn't contain any calories.");
        englist.add("Virginity is not dignity, It is just lack of opportunity.");
        englist.add("Sorry... I'm not Rihanna. I don't love the way you lie.");
        englist.add("God made everything that has life, rest everything is made in China :)");
        englist.add("People who wait 4 hours to reply to a text with “lol” should be shooted :)");
        englist.add("Dear Sleep! I Know We Had Problems When I Was Younger! But NOW I Lubbb you :-D");
        englist.add("I look at people sometimes and think ..... Really?? That's the sperm that won :)");
        englist.add("The only thing that interferes with my learning is my education.");
        englist.add("We are all in the same game, just different levels. Dealing with the same hell, just different devils.");
        englist.add("In bed, it's 6AM you close your eyes for 5 minutes, it's 7:45. At school it's 1:30, close your eyes for 5 minutes, it's 1:31");
        englist.add("It may look like I'm deep in thought, but 99% of the time I'm just thinking about what food to eat later.");
        englist.add("Friday is my second favorite F word.");
        englist.add("If there’s one thing I hate the most, its seeing bad things happen to good people.");
        englist.add("I know I’m crazy. Don’t ruin my moment.");
        englist.add("When I'm a Pedestrian I Hate cars.. When I'm Driving I Hate Pedestrians.");
        englist.add("Girls, if he only wants your breasts, legs, and thighs. send him to KFC.");
        englist.add("Never apologize for being you.");

        if (isNetworkConnected()) {
            rajputlist.setVisibility(View.VISIBLE);
            Net_connection.setVisibility(View.GONE);

        } else {
            rajputlist.setVisibility(View.GONE);
            Net_connection.setVisibility(View.VISIBLE);
        }

        rjptadapter = new Shayri_Adapt(getActivity(), englist, "rjpthindi");
        rajputlist.setAdapter(rjptadapter);

        return view;
    }

    private boolean isNetworkConnected() {
        ConnectivityManager cm = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);
        return cm.getActiveNetworkInfo() != null && cm.getActiveNetworkInfo().isConnected();
    }

}