package ind.apptech.captionsforinstagram.fragment;

import android.content.Context;
import android.net.ConnectivityManager;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.RecyclerView;
import androidx.recyclerview.widget.StaggeredGridLayoutManager;

import ind.apptech.captionsforinstagram.Shayri_Adapt;
import com.apptech.captionsforinstagram.R;

import java.util.ArrayList;

public class Funny extends Fragment {

    RecyclerView rajputlist;
    Shayri_Adapt rjptadapter;
    ArrayList<String> englist = new ArrayList<>();
    private RecyclerView.LayoutManager layoutManager;
    LinearLayout Net_connection;

    public Funny() {
        // Required empty public constructor
    }

    public static Funny newInstance(String param1, String param2) {
        Funny fragment = new Funny();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.hindi_shayri, container, false);

        rajputlist = (RecyclerView) view.findViewById(R.id.English_list);
        Net_connection = view.findViewById(R.id.Net_connection);
        layoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.VERTICAL);
        rajputlist.setLayoutManager(layoutManager);

        englist = new ArrayList<>();

        englist.add("Life is too short, smile while you still have teeth..");
        englist.add("I’m not getting older, I’m just becoming a classic..");
        englist.add("Lary is wondering if they could invent a self cleaning oven, why can’t they invent a self cleaning house?");
        englist.add("Milk does the body good but DAMN how much did you drink?");
        englist.add("Just finished deleting some friends on Facebook, if you can read this then you got lucky.");
        englist.add("If people have a problem with u, always remember, it is THEIR problem..");
        englist.add("I’m the kind of person who bumps into inanimate objects, says, Oops, I’m sorry. And doesn’t stop to ask himself why he’s talking to a wall.");
        englist.add("Most emotional moment in a boys life, When a girl says, Can you give me your number :D");
        englist.add("The first half of our life is ruined by our parents and the second half by our children.");
        englist.add("I hate when skinny girls say,”omg I’m so fat”. If you are fat does that make me a whale?");
        englist.add("Can I take your picture?? I love to collect pictures of natural disasters.");
        englist.add("One of my mom’s rules growing up was never to write on walls, well apparently Facebook doesn’t have that rule.");
        englist.add("Next time someone presses the elevator button you’ve already pressed, act totally impressed and tell them they did it waaaay better than you..");
        englist.add("Don’t kiss behind the garden, Love is blind but the neighbours are not.");
        englist.add("Sleep is so cute when it tries to compete with the internet…");
        englist.add("Don’t be afraid to make mistakes..");
        englist.add("Dear math, Im not therapist so solve your own problems.");
        englist.add("If I get jealous then yes I really like you.");
        englist.add("If at first you don’t succeed, cheat, repeat until caught, and then lie!");
        englist.add("I don’t usually sleep enough, but when I do, it’s still not enough ;)");
        englist.add("A woman is like a tea bag, you cannot tell how strong she is until you put her in hot water.");
        englist.add("Only fools fall in love and I guess I’m one of them :)");
        englist.add("I never make the same mistake twice. Three, four times maybe. But never twice.");
        englist.add("Don`t you know it`s rude to talk while I`m interrupting?");
        englist.add("It’s Christmas and 2011 is coming closer to an end! what’s the funniest thing you remember me doing this year??");
        englist.add("Facebook is like a fridge. When you’re bored you keep opening and closing it every few minutes to see if there’s anything good in it.");
        englist.add("?  Behind this smile is everything you’ll never understand.");
        englist.add("I always learn from mistake of others who take my advice :)");
        englist.add("Excuse me …. Plesae empty your pockets …. I think you stole my heart.");
        englist.add("TODAY has been cencelled. Go back to BED :)");
        englist.add("You can't make someone love you. you can only talk them and hope for the best. :P");
        englist.add("I`m jealous of my parents, i`ll never have a kid as cool as theirs…");
        englist.add("Taking revenge is wrong… very very wrong… But very very fun…");
        englist.add("It`s too late to apologize. The damage is done.");
        englist.add("Read books instead of reading my status!");
        englist.add("Math questions are so stupid! They’re like “If I have 5 bottles in one hand and 6 in the other, what do I have?” Oh I dunno, a drinking problem maybe?");
        englist.add("If you like me press like. If you hate me, go away. If you love me comment.");
        englist.add("Today’s Joke! A Girl said …….. TRUST ME :)");
        englist.add("Dear Google, Please stop behaving like a GIRL. Will u please allow me to complete the whole sentence before you start guessing & suggesting.");
        englist.add("Tired of everyone talking about their feelings on Facebook lol..");
        englist.add("thinks that facebook should change the status question from “what’s on your mind?” to “what’s your problem today?”");
        englist.add("When a woman says WHAT? Its not because she didn’t hear you. She’s giving you a chance to change what you said.");
        englist.add("Happiness is when last seen at changes to online and then to typing :P");
        englist.add("Growing older is compulsory Growing up, however, remains optional.");
        englist.add("I think all woman can agree that bigger is better. Nobody wants a small bank account");
        englist.add("Girls are funny creatures.They hate it when you ask their age but will kill you if you forget their birthday!!!");
        englist.add("Can’t talk, telepathy only!");
        englist.add("Stealing other people’s statuses on Facebook is called a Facelift.");
        englist.add("It’s not true that I had nothing ON….. The radio was ON. :)");
        englist.add("Love is 1 drink and 2 straws. Marriage is “Don’t you think you’ve had enough!”.");
        englist.add("My girlfriend asked if I would swim across the ocean for her, and I said It’s freaking, I’ll rent a boat…..");
        englist.add("If there is no chocolate in heaven…”I AM NOT GOING”.");
        englist.add("Do your legs hurt from running through my dreams all night?");
        englist.add("I’m usually charming, nice, and well manured, OK for those who really know me you can laugh now..");
        englist.add("I don’t always lose my phone but when I do its always on silent :)");
        englist.add("Insert coin to view my status message.");
        englist.add("My “last seen at” was just to check your “last seen at”.");
        englist.add("I’m not arguing, I’m simply tried to explaining why I’m Right.");
        englist.add("You look like a cool glass of refreshing water, and I am the thirstiest man in the world.");
        englist.add("I have enough money to last me the rest of my life, unless I buy something.");
        englist.add("Young love is two hearts with only one thing in mind.");
        englist.add("An apple a day keeps the doctor away, but if doctor is cute, forget the fruit.");
        englist.add("A man typed in search box on Google : “What do women want?”. Google Replied : “We are also searching…”");
        englist.add("Marriage is like going to a restaurant and order your choice from the menu, And then look at neighbouring table n wish you”d ordered that.");
        englist.add("My parents told me: “You’ve got to stop watching so much TV, and read more!” so I turned on the subtitles.");
        englist.add("If a single teacher can’t teach all the subjects then how could you expect a single student to learn all subjects.");
        englist.add("You wanna see a perfect relationship? Watch a movie. Lolz");
        englist.add("I posted on your wall. No, not Facebook, look at the side of your house.");
        englist.add("Doing the moonwalk is the only way to look cool while wiping dog crap off your shoes.");
        englist.add("I want some one to give me a Loan and then leave me Alone.");
        englist.add("I hate math but I love counting money.");
        englist.add("I follow the quote, “Always be true to yourself” because I only lie to others!");
        englist.add("I think I got a fever, a fever of you :)");
        englist.add("Dear parents, we know money doesn’t grow on trees, that’s why we are asking you for it.");
        englist.add("Hey, I found your Nose, it was in my business again.");
        englist.add("I feel like a Indiana Jones, because you are the treasure I am looking for.");
        englist.add("Between Facebook texting, tweeting and email, I haven’t spoken a word in the last 3 years.");
        englist.add("If vegetarians eat only vegetables, what about humanitarians?");
        englist.add("Today morning when I was driving my Ferrari, the alarm woke me up. :)");
        englist.add("Some people talk in their sleep. Lecturers talk while other people sleep.");
        englist.add("I only need 3 things in life: Food, Wifi, Sleep :)");
        englist.add("If people could see the face I make when I read their facebook status updates, they would probably unfriend me.");
        englist.add("Behave, What you do today will be on Facebook tomorrow.");
        englist.add("Your eye is the only part you can not wash with soap.");
        englist.add("Some people are such treasures that you really just wanna bury them.");
        englist.add("I did in the bed. I did it on the couch. I did it in the car. Texting is such an obsession. :)");
        englist.add("How can i miss something i never had?");
        englist.add("Etc= End of thinking Capacity.");
        englist.add("It’s funny how people judge other’s mistakes while they also do the same thing.");
        englist.add("The awkward moment when you know you shouldn`t laugh, but you do..");
        englist.add("Laughing is the best medicine but if you are laughing for no reason, you need medicine.");
        englist.add("Bad decisions make good stories. No wonder people find me so entertaining..");
        englist.add("You and your rumors have two things in common, you’re both fake and you both get around.");
        englist.add("If school has taught us anything, it’s texting without looking :)");
        englist.add("WARNING!! I know karate …..and some other words!!!");
        englist.add("It’s just Facebook, I wish people would keep it real and stop frontin.");
        englist.add("Someone on his status Sleeping ...since 3 Days! He's Probably dead.");
        englist.add("There are no stupid questions, just stupid people..");
        englist.add("Laziness is my middle name.");
        englist.add("Not all men are fools, Some stay bachelor.");
        englist.add("The first five days after the weekend are always the hardest.");
        englist.add("If you want to commit suicide, you should jump down from your ego to your IQ.");
        englist.add("Is your name Summer.? because you are as hot as hell.");
        englist.add("For you men who think a woman’s place is in the kitchen, remember thats where the knives are kept. :)");
        englist.add("That awkward moment when you say goodbye to someone and you end up walking in the same direction.");
        englist.add("Forget love, I’d rather fall in chocolate.");
        englist.add("Vote Up Vote Down My Facebook wall is broken.");
        englist.add("Getting married is a lot like getting into a tub of hot water. After you get used to it, it ain’t so hot.");
        englist.add("I'm Jealous of My Parents... I'll Never Have a Kid as Cool as Theirs!!!");
        englist.add("Money can’t buy happiness, but it pays for internet, which is pretty much the same thing.");
        englist.add("Math Rule: If it seems easy, you’re doing it wrong.");
        englist.add("Thinks I feel great when I go to bed drunk. I wake up feeling crap. Obviously sleep is bad for you.");
        englist.add("Why is it called lipstick if you can still move your lips?");
        englist.add("Silence is the best answer of all questions and Smile is the best reaction in all situations. Unfortunately both never help in VIVA & INTERVIEW.");
        englist.add("Women are like boats: they require constant maintenance and attention, and they cost a lot of money. Men are like buses: another one will eventually come along.");
        englist.add("One day, I’m gonna make the onions cry..");
        englist.add("I don’t have issues, I have demonds and they are the ones with issues");
        englist.add("Do you ever just lie on knees and thank god that you know me and my intelligence???");
        englist.add("I hate when my mind wont shut up when I’m trying to sleep..");
        englist.add("I don’t believe that love comes to those who wait. Today love comes to those who flirt. LOLz");
        englist.add("Scratch here ¦¦¦¦¦¦¦¦¦¦¦¦¦¦ to reveal this status.");
        englist.add("I’m not failed…my success is just postponed for some time.");
        englist.add("How to make a woman go mmmmmmm all nite long? …………………….. with Duct Tape :)");
        englist.add("Men are like buses. One comes every 15 minutes.");
        englist.add("I believe in hate at first sight.");
        englist.add("I’m not weird. I’m limited edition.");
        englist.add("If life give you lemons, squirt your enemy’s eye..");
        englist.add("C.L.A.S.S – Come Late And Start Sleeping");
        englist.add("Why can’t shampoo and conditioner run out at the same time?");
        englist.add("If you can’t beat them, arrange to have them beaten.");
        englist.add("We all are born to die don’t feel more special than me.");
        englist.add("If you try and don’t succeed, cheat. Repeat until caught. Then lie.");
        englist.add("I never get mad when i see my ex with someone else because i was always taught to recycle my old trash.");
        englist.add("Im a math teacher. One plus two equals me and you");
        englist.add("Girls work on their looks but not their minds b’coz they know boys are stupid, not blind.");
        englist.add("If Facebook is like dating, then Twitter is like a one night stand – it’s fun while you’re doing it, you finish in like 5 minutes, and you feel real cheap afterwards.");
        englist.add("Facebook is the only place where it’s acceptable to talk to a wall.");
        englist.add("Girls fall in love with what they hear. Boys fall in love with what they see. That’s why girls wear make up and boys lie.");
        englist.add("If someone throws a rock at you, throw a flower back at them, but, make sure the flower is still in the pot..");
        englist.add("Worrying works! 90% of the things I worry about never happen.");
        englist.add("I bet that in prison everyone’s FB relationship status is set to it’s complicated.");
        englist.add("Some people should just give up at engineering( or medical) ………i have.");
        englist.add("Please GOD if you can’t make me slim, make my friends fat.");
        englist.add("Tip to reduce weight, first turn your head to the left and then turn it to the right. Repeat this exercise every time you are offered something to eat.");
        englist.add("Boys think of girls like books; if the cover doesn’t catch their eyes, they won’t even bother to read what’s inside.");
        englist.add("I have a date tonight, with my bed. We are totally gonna sleep together.");
        englist.add("When your GF blocks u on facebook…… Its called an electronic divorce :)");
        englist.add("I come up with the best ideas when sitting on the toilet then forget them after the flush.");
        englist.add("My friend wants to know if you think I’m hot.");
        englist.add("I wish I could google “things to eat in my fridge” so I wouldnt have to go downstairs and be disappointed.");
        englist.add("People say everything happens for a reason. So when I punch you in the face, remember I have a reason. ;-)");
        englist.add("Relationship Status: Looking for a WiFi connection.");
        englist.add("Teacher: Who can explain gender discrimination with an example? Student: Women can sleep with whoever they want ,men have to sleep with whoever lets them!");
        englist.add("Why is abbreviation such a long word?");
        englist.add("All my life I thought air is free until I bought a bag of chips.");
        englist.add("Behind every successful man is his woman. Behind the fall of a successful man is usually another woman.");
        englist.add("It’s raining, It’s pouring. Facebook is boring. I’m bored to death, I’m going to bed, hopefully we’ll meet in the morning!");
        englist.add("I have a Date tonight, Woot Woot! (of course its with the couch, pillow and TV Remote, but its still a date. Right?)");
        englist.add("Who care’s ?????………..I’m awsome!!!");
        englist.add("How do people write an auto biography? I can barley remember what I had for lunch yesterday :)");
        englist.add("Don’t steal, don’t lie, don’t cheat, don’t sell drugs. The government hates competition..");
        englist.add("We are best friends. Always remember that if you fall, I will pick you up …….. after I finish laughing :)");
        englist.add("Your time, energy and love is precious make sure that it is not wasted and preciously invested when dating.");
        englist.add("Thanks to Google, Wikipedia, and whoever the hell invented copy and paste. Thank you Guys.");
        englist.add("Only Marriage is the major cause of divorce.");
        englist.add("Restaurant Advertisement: We serve food as HOT as your neighbour’s wife; And beer as COLD as your own. :)");
        englist.add("Never make the same mistake twice, There are so many new ones, Try a different one each day.");
        englist.add("Where there is a will, there are 100 relatives.");
        englist.add("Dear Facebook, Just wait, one day they will leave you too. Sincerely, ORKUT");
        englist.add("I’m not weird, I’m limited edition.");
        englist.add("If you can’t find the key to success, pick the lock.");
        englist.add("I don`t have a bad handwriting, I have my own font.");
        englist.add("Facebook is a crazy house People poke each other all day have an imaginary pet farm and talk to walls");
        englist.add("I didnt change , i just grew up. You shud try it once ;)");
        englist.add("Excuse me, if I go straight this way, will I be able to reach your heart?");
        englist.add("Job interview: Please tell us why you’d love to work for us? ME: I need money :)");
        englist.add("Congratulations … You are the 100th person to view my status. To see your prize please click Control + W.");
        englist.add("Is there anything more awkward than when you are singing along to a song on youtube and the music stops loading.");
        englist.add("There are two types of human beings found on Facebook. One who gets enormous amount of likes and comments on their posts. And the others are men.");
        englist.add("Its better to fail than to cheat but its better to cheat than to repeat.");
        englist.add("You know what? Your eyes are the same color as my Porsche.");
        englist.add("Okay mom…you know I love you…but I can’t accept your friend request on Facebook.");
        englist.add("If you love someone, set them free. If they come back, nobody else wanted them either :)");
        englist.add("Well, We have a poke button, now we need a punch and pinch and kick button..");
        englist.add("For every girl without a guy, there`s a guy without a girl.");
        englist.add("Do you know the meaning og ABCDEF? A boy can do everything for Girl. Reverse the meaning of, GFEDCBA … Girl forget everything done & Catches new boy Again.");
        englist.add("Flirtationship: More than a friendship and less than a relationship.");
        englist.add("Hey,you are reading my status again??");
        englist.add("Did anyone ever notice that “STUDYING” is a mixture of STUDY and DYING?");
        englist.add("I may be old enough to know better, but I am STILL young enough to DO IT..");
        englist.add("Doing nothing is very hard thing to do…you never know when to finish.");
        englist.add("Laziness is me middle name.");
        englist.add("Do you know the difference between a lady and a woman? A lady does what she’s told and a woman does what she dam well pleases!");
        englist.add("When a newly married man looks happy, we know why. But when a ten year married man looks happy, we wonder why.");
        englist.add("Want to learn how to dance? Have a cold shower today at midnight, I bet, You’ll rock like SHAKIRA :)");
        englist.add("Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.");
        englist.add("Boys, if you don’t look like calvin klein models, don’t expect us to look like victoria secrets angels. (From All Bachelor Girls Association) :)");
        englist.add("The secret to success is knowing who to blame for your failures.");
        englist.add("If women ruled the world there would be no wars. Just a bunch of jealous countries not talking to each other.");
        englist.add("I heard you took an IQ test and they said you’re results were negative.");
        englist.add("If Barbie is so popular, why do you have to buy her friends?");
        englist.add("Every girl deserves ONE GUY who looks at her every day like it’s the first time he saw her. And Im that ONE GUY :)");
        englist.add("If life gives you lemons, just add vodka.");
        englist.add("When someone adds me as a friend on Facebook, the first thing I do is go through all their pictures.");
        englist.add("There are only two kinds of people in this world: Doctors and Patients :)");
        englist.add("I’m not single, I’m just romantically challenged.");
        englist.add("My wifi suddenly stop working then I realized that my neighbors have not paid the bill. How irresponsible people are.");
        englist.add("I was good at math before they decided to mix the alphabet in it.");
        englist.add("You have eyes my dear but you cannot see.");
        englist.add("If you love something, let it go. If it comes back, it was meant to be. If it does not, hunt it down & kill it.");
        englist.add("While waiting for the right person, have fun with the wrong one.");
        englist.add("I’m the person that the more you complain about me, the harder I’ll try to annoy you.");
        englist.add("For all the girls that say ….. All guys are the same …… Who told you to try them ALL.");
        englist.add("It’s funny when people discuss Love Marriage vs Arranged. It’s like asking someone, if suicide is better or being murdered.");
        englist.add("When you’re good, you’re good, when you’re awesome you’re me..");
        englist.add("Knowledge is like underwear. It is useful to have it, but not necessary to show it off.");
        englist.add("The real reason women live longer than men b’coz they don’t have to live with women.");
        englist.add("A black cat passing by the crossroad can stop hundreds of people what a RED LIGHT on traffic signal has failed to do for long time!!");
        englist.add("Laughing at your own texts before you send them because you are so damn funny.");
        englist.add("Full form of study - S-T-U-D-Y = [S]inging, [T]weeting, [U]nlimited Texting, [D]reaming, [Y]awning.");
        englist.add("Friday is my second favorite F word.");
        englist.add("I hate when I am about to hug someone really sexy and my face hits the mirror.");
        englist.add("One day your prince will come. Mine just took a wrong turn, got lost and is too stubborn to ask for directions :)");
        englist.add("There are alot of fish in the sea, but I think there’s a hole in my net :)");
        englist.add("The problem is not the problem; the problem is your attitude about the problem.");
        englist.add("Married men should forget their mistakes. There is no need for two people, to remember the same thing.");
        englist.add("Never Say Neverrr, you just said it twice ?");
        englist.add("I wish i have a friend like me  :D");
        englist.add("If bar tenders aren’t allowed to sell alcohol to drunk people, then McDonald’s shouldn’t be allowed to sell food to fat people.");
        englist.add("I need 6months vacation, twice a year..");
        englist.add("Nothing moves faster than a girl untagging herself from an ugly picture :)");
        englist.add("The secret of a happy marriage remains a secret.");
        englist.add("Brain is a wonderful organ. It starts working the moment you get up in the morning and does not stop until you get into the office.");
        englist.add("One should always be in love. That is the reason one should never marry.");
        englist.add("I speak my mind. I never mind what I speak.");
        englist.add("I had my DNA analyzed. It came back with four main components. Bacon, Chocolate, Coffee & Crazy.");
        englist.add("My friend has just updated his status saying. Is balancing on the edge of a cliff.. So i poked him.");
        englist.add("When a bird hits your window have you ever wondered if God is playing angry birds with you?");
        englist.add("life is short…smile while you still have teeth.");
        englist.add("Before talking, Please connect the tongue to the brain…");
        englist.add("Some people like my advice so much that they frame it upon the wall instead of using it.");
        englist.add("Do You Want To Go Out With Me? (A) Yes (B) A (C) B.");
        englist.add("My name is I. My problem is love. My solution is you.");
        englist.add("Just saw the most smartest person when i was in front of the mirror :P");
        englist.add("I don’t understand how Super Mario can smash blocks with his head but dies when he touches a turtle.");
        englist.add("Do you realize that in about 40 years, we’ll have thousands of old ladies running around with tattoos?");
        englist.add("Boys will be boys as long as there are no girls in the picture.");
        englist.add("I love my six pack so much, I protect it with a layer of fat :)");
        englist.add("Dear smartphones, why can`t you charge yourself? Sincerely, you`re not so smart after all.");
        englist.add("Quit your job, buy a ticket, get a train, fall in love and never return.");
        englist.add("It is a sad fact that 20% of marriages in this country end in divorce. But hey, the remaining end in death. You could be one of the lucky ones.");
        englist.add("Whatever you do always give 100% ….. Unless you are donating blood :)");
        englist.add("Most mothers feed their babies with little spoons and forks. What do Chinese mothers use? Toothpicks?");
        englist.add("I never let my best friend do stupid things … alone.");
        englist.add("Boyfriend: Do you think my salary is sufficient for you? Girlfriend: It’s sufficient for me but how will you survive?");
        englist.add("You can disturb me….I’m available. :D");
        englist.add("I love buying new things but I hate spending money.");
        englist.add("Hey, you have eyes, I have eyes, we have a lot in common!");
        englist.add("I am going to start cleaning my house. And by cleaning, i mean drinking beer and spraying everything with febreze.");
        englist.add("It’s been 70+ years, Tom. You’re never going to eat Jerry :)");
        englist.add("Girls are funny creatures. They hate it when you ask their age but will kill you if you forget their birthday.");
        englist.add("Dear Ceiling Fan, If you could hold my weight, i would never be bored again. Sincerely, Bored.");
        englist.add("The Earth without Art is just Eh.");
        englist.add("Don’t you hate when the person you’re Facebook talking never updates anything.");
        englist.add("The question I have not been able to answer is “What… does a woman want?”");
        englist.add("I don’t get it, all my life I was told NOT to write on walls.");
        englist.add("Harush says if you want to be together you have TO-GET-HER.");
        englist.add("I’m not stalker. I am an unpaid private investigator.");
        englist.add("You can’t put a price tag on love, but you can on all its accessories.");
        englist.add("I always give 100% at work: 13% Monday, 22% Tuesday, 26% Wednesday, 35% Thursday, 4% Friday :)");
        englist.add("The zoo is a pretty safe place to fart.");
        englist.add("You have lot of curves and I have no brakes ;)");
        englist.add("If Facebook is the Upper West Side and MySpace is the Bronx, then Tagged is a trailer park in New Jersey.");
        englist.add("When nothing seems right….go left!!");
        englist.add("Hi, Im Mr Right. Someone said you were looking for me.");
        englist.add("Facebook, because time isn’t going to kill itself.");
        englist.add("I love my job only when I’m on vacation.");
        englist.add("The definition of a beautiful girl is one who loves me :)");
        englist.add("I really need a day in between Saturday and Sunday :)");
        englist.add("It’s amazing that the amount of news that happens in the world each day fit exactly the length of newspaper!!");
        englist.add("The human brain is amazing. It functions 24 hours a day from the time we were born, and only stops when we take exam or are in love.");
        englist.add("God made everything that has life, rest everything is made in China :)");
        englist.add("Even if you live your life as a open book, people will still wonder which pages have secret messages.");
        englist.add("Don’t do it in the Garden, they say love is blind but ur neighbor ain’t. :)");
        englist.add("I know that somewhere in the Universe exists my perfect soulmate … but looking for her is much more difficult than just staying at home and ordering another pizza.");
        englist.add("I have finally figured out why I can’t lose this extra weight. The shampoo I use in the shower that runs down my body says, “for extra volume and body.”");
        englist.add("I’m not sure how much longer I can hide the fact that I’m a robot.");
        englist.add("If life gives you questions, Google gives you answers.");
        englist.add("Instead of single as a marital status, it should read independently, owned and operated :)");
        englist.add("A lot of people are afraid of heights. Not me, i am afraid of widths.");
        englist.add("I’m just having an allergic reaction to the universe.");
        englist.add("Good friends will bail you out of jail. Best friends will be sitting in the cell with you, laughing about how awesome that just was.");
        englist.add("Never make the same mistake twice. There are so many new ones to make.");
        englist.add("There’s always a person that you hate for no reason.");
        englist.add("I believe we should all pay our tax with a smile. I tried – but they wanted cash.");
        englist.add("The most powerful words other than I LOVE YOU is “Salary is Credited” :)");
        englist.add("Women are like police, they can have all the evidence in the world but they still want a confession.");
        englist.add("BRB = I don’t want to talk to you. LOL = I have nothing else to say. Cool = I don’t care.");
        englist.add("Never get into fights with ugly people, they have nothing to lose.");
        englist.add("When I’m on my death bed, I want my final words to be “I left one million dollars in the…");
        englist.add("Do you know why a previous relationship is called EX? It`s not the term for the past. EX is short for EXpired..");
        englist.add("Finally found out that the plant I’ve been watering isn’t real…");
        englist.add("Awesome ends with ME and Ugly starts with you.");
        englist.add("I really need 5 hours of Facebook to balance out my 5 minutes of studying.");
        englist.add("I love it when someone’s laugh is funnier than the joke.");
        englist.add("The police are on the way to arrest you for stealing my heart, hijacking my feelings, and driving me crazy.");
        englist.add("If you fall. I’ll be there.");
        englist.add("That awkward moment, when you wake up with one sock on.");
        englist.add("The only difference between me and a madman is that I’m not mad.");
        englist.add("Doctors finally figured out whats wrong with a boys brain; on the left side, there’s nothing right; and on the right side, there’s nothing left…");
        englist.add("In bed, it’s 6AM you close your eyes for 5 minutes, it’s 7:45. At school it’s 1:30, close your eyes for 5 minutes, it’s 1:31");
        englist.add("Facebook is the second most popular word that starts with ‘F’ and ends with ‘K’ :)");
        englist.add("I speak two languages, Body and English.");
        englist.add("Running away does not help you with your problems, unless you are fat.");
        englist.add("If you are reading this, congrats you know how to read..");
        englist.add("Ladies first. Pretty ladies sooner. :)");
        englist.add("Opportunity knocks for every man, but you have to give a woman a ring.");
        englist.add("A man asks a trainer in the gym: I want 2 impress that beautiful girl , which machine can I use? Trainer replies: Use the ATM");
        englist.add("I am not addicted to Facebook. I only use it when I have time . . . . . . . . . lunch time, break time, bed time, this time, that time, any time, all the time. :)");
        englist.add("You don’t have to like me, I’m not a Facebook status.");
        englist.add("Nothing is illegal until you get caught :)");
        englist.add("Admit it, you listen to other strangers conversations and mentally give your opinion.");
        englist.add("Sometimes at home I talk in my sleep, but at school I sleep while others are talking.");
        englist.add("If I’m wired with you. I like you.");
        englist.add("Love thy neighbor. But don’t get caught.");
        englist.add("Bachelors should be heavily taxed. It’s not fair that some men should be happier than others.");
        englist.add("I’m a smart person, I just do stupid things.");
        englist.add("Everything I like is either Illegal, Immoral, Fattening, Addictive, Expensive, or Impossible.");
        englist.add("Don’t drink and park – accidents cause people.");
        englist.add("I hate when people all of a sudden decide to be funny when I am drinking something :)");
        englist.add("you`re sorry ? that`s cool. go write a book about it and let someone who actually cares read it.");
        englist.add("Every problem comes with a solution. If it doesn’t have any solution, it’s a…………. Girl :)");
        englist.add("Ah, Facebook, where it is socially acceptable to talk to a wall…");
        englist.add("If you wish to avoid seeing a fool, you must break your mirror :D");
        englist.add("Years of education, solving tough problems, handling complex issues, yet we take a while standing before glass doors thinking whether to Push or Pull.");
        englist.add("Men are like BLUETOOTH connection, when UR beside them they stay connected but when you are away they search for new devices.");
        englist.add("The only thing I gained so far in 2013 is weight :)");
        englist.add("I’m not 40, I’m eighteen with 22 years experience…");
        englist.add("People say nothing is impossible, but I do nothing every day.");
        englist.add("BOY-aaye the, hum padh rahe the wo coaching smajh kar chale ");
        englist.add("I used to like my neighbours, until they put a password on their Wi-Fi :)");
        englist.add("Newton’s law of love: Love can neither be created nor be destroyed. Only it can transfer from one girlfriend to another with some loss of money.");
        englist.add("I look at people sometimes and think ….. Really?? That’s the sperm that won :)");
        englist.add("A man is incomplete until he is married. After that, he is finished.");
        englist.add("When you really want to slap someone, do it and say “mosquito.”");
        englist.add("Do you know what’d look good on you? Me :)");
        englist.add("Try to say the letter M without your lips touching.");
        englist.add("Sometimes the only one who can appreciate you, is you.");
        englist.add("I hate people who steal my ideas, before I think of them :)");
        englist.add("Can I buy you a drink, or do you just want the money?");
        englist.add("I am a star, so when you see me, make a wish.");
        englist.add("I haven’t slept for ten days, bcoz that would be too long.");
        englist.add("Stop waiting for one Day. Today is the Day- Bang-Bang");
        englist.add("Don’t steal, don’t lie and don’t cheat. The government hates competition.");
        englist.add("We are the WTF generation: Wikipedia, Twitter and Facebook.");
        englist.add("Remember, when she cancels a date she has to But when he cancels a date he has TWO.");
        englist.add("When it’s you against me, you either win or you die!!!");
        englist.add("When I Show you a picture on my phone..don’t swipe left.don’t swipe right.Just look.");
        englist.add("Don’t take life too seriously, you won’t get out of it alive.");
        englist.add("Definition of human being: a creature that cuts trees, makes paper & write “SAVE TREES” on the same paper.");
        englist.add("If swimming is an exerciser explain whales to me.");
        englist.add("Life is hard normally, but its harder if you are Stupid.");
        englist.add("Bitch also stands for beautiful, intelligent, talented and charming human being.");
        englist.add("Hmmmm…..Don’t copy my status");
        englist.add("Love your girl like you love your Coffee… Enjoy it before its hotness goes.");
        englist.add("That awkward moment when you keep talking & you don`t realize your friend walked away.");
        englist.add("Question of the Day: When you wait for a waiter in a restaurant, aren’t you a waiter?");
        englist.add("The best way to look younger, hang out with older people.");
        englist.add("I always learn from mistakes of others, who took my advice :)");
        englist.add("Can I take your picture?? I love to collect pictures of natural disasters..");
        englist.add("Facebook is like jail, you sit around and waste time, write on walls, and get poked by people you don’t know.");
        englist.add("Why do you talk so fast?” “Why do you listen so slow?”");
        englist.add("My study period = 15 minutes. My break time = 3 hours.");
        englist.add("My bed is always extra comfortable when I need to get out of it in the morning.");
        englist.add("Kiss me and you will see how important I am.");
        englist.add("I have enough money to live comfortably for the rest of my life, If I die next Tuesday.");
        englist.add("We are WTF generation …. WhatsApp, Twitter and Facebook :D");
        englist.add("The 3 fastest means of communication: telephone, television and tell a woman.");
        englist.add("I want you to have a candle-lit dinner and say those magical three words to you ………… “Pay The bill”");
        englist.add("If you stop telling lies about me, I’ll stop telling the truth about you.");
        englist.add("God is really creative , i mean ..just look at me :P");
        englist.add("Marriage is a relationship in which one person is always right and the other is the husband!");
        englist.add("The two most common elements in the universe are hydrogen and stupidity.");
        englist.add("Dear Lord, all I ask for a chance to prove that winning the lottery won’t make a bad person.");
        englist.add("Having a best friend with the same mental disorder is a blessing. LOL");
        englist.add("God must love stupid people. He made SO many.");
        englist.add("The average woman would rather have beauty than brains, because the average man can see better than he can think.");
        englist.add("The hardest job facing kids today is to learn good manners without seeing any.");
        englist.add("I’d like to thank the internet, Google, Wikipedia, Microsoft Word, and Copy & Paste :)");
        englist.add("I think my iPhone is broken. I pressed the home button and i’m still at school.");
        englist.add("You`re beautiful until your Photoshop 30 day trial has gone.");
        englist.add("When I drink alcohol… Everyone says I’m alcoholic. But… When I drink Fanta.. No one says I’m fantastic!!!");
        englist.add("You can not get lost on a straight road.");
        englist.add("People say laughter is the best medicine. Your face must be curing the world.");
        englist.add("Money doesn`t bring happiness, but shopping does..");
        englist.add("My family says I talk in my sleep but nobody at work has ever mentioned it. Lolz");
        englist.add("Facebook is the adult way of having imaginary friends.");
        englist.add("They say that alcohol kills slowly. So what? Who’s in a hurry?");
        englist.add("You dont realise how many clothes you have, until you wash them.");
        englist.add("I don’t always lose my phone but when I do its always on silent.");
        englist.add("Thinks if Peter Piper picked peppers and Jack and Jill ran up the hill and Mary took her lamb to school, wasn’t Humpty Dumpty lazy just sitting on a wall?");
        englist.add("If money grew on trees – girls wouldn’t mind dating monkeys.");
        englist.add("GOOGLE must be a woman because it knows everything.");
        englist.add("Dear MATH, stop asking to find your X, she’s not coming back.");
        englist.add("I am sure I have a defective iphone, I keep pressing the home button and I’m still at work.");
        englist.add("We love Facebook but we hate the face of book.");
        englist.add("Women only need 3.5 inches to achieve maximum pleasure, it’s called a credit card.");
        englist.add("Caution, Blind Man Driving.");
        englist.add("The only thing that interferes with my learning is my education.");
        englist.add("Out of my mind. Back in five minutes.");
        englist.add("Men are like parking spaces; The good ones are taken, and the only ones left are handicapped.");
        englist.add("I am not feeling lazy actually, I am just incredibly motivated to do nothing..");
        englist.add("Sorry, I can’t hangout. My uncle’s cousin’s sister in law’s best friend’s insurance agent’s roommate’s pet goldfish died. Maybe next time..");
        englist.add("Todays Relationships: You can touch each other but not each others phones.");
        englist.add("FACT: Kissing burns 5.4 calories a minute…… Ummm, wanna work out?");
        englist.add("When a girl says she’ll be ready in 5 more minutes, it’s the same as when a guy says the game has 5 minutes left. :D");
        englist.add("If couples who are in love are called LOVE BIRDS, then couples who always argue should be called ANGRY BIRDS");
        englist.add("I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.");
        englist.add("Dear Google, thank you for doing most of my homework for me. :)");
        englist.add("Rumors are carried by haters, spread by fools, and accepted by idiots..");
        englist.add("In victory, you deserve Champagne. In defeat you need it.");
        englist.add("Why do U think I SMS You? Is it because I care? Or I miss You? Or I love You? Or I need You? No ! It’s because I need a person for just time pass. :)");
        englist.add("How to sleep faster: Decorate your bedroom to look like a classroom.");
        englist.add("My life, My choices, My mistakes, My lessons, Not your business.");
        englist.add("There’s like 7 billion people in this world and no one wants to date me. I hate this world … huh");
        englist.add("I promised my friends that I wouldn’t date bad girls anymore.");
        englist.add("If you are player then I’m the GAME.");
        englist.add("Why does paper beat rock? if you hold a paper in front of your face and i throw a rock at it who wins?");
        englist.add("If you are supposed to learn from your mistakes, why do some people have more than one child.");
        englist.add("If you can’t convince them, Confuse them.");
        englist.add("Some people call me Mike, You can call me tonight.");
        englist.add("I wonder if I've met the person I’m going to marry.");
        englist.add("Viagra is now available in powder form to put in your tea. It does not enhance your performance but it does stop your biscuit going soft. Lolz");
        englist.add("just found out that if you hold Ctrl and w for 10 seconds it turns your Facebook page from Blue to Red");
        englist.add("People say everything happens for a reason. So when I punch you in the face, remember I have a reason. ;-)");
        englist.add("Dear Food, Either stop being so delicious or stop making me fat :)");
        englist.add("It used to be, “Can I have your number”? Now it’s, Do you have Facebook..");
        englist.add("I wonder what happens when doctor’s wife eats an apple a day. :)");
        englist.add("I want some one to give me a Loan and then leave me Alone. :)");
        englist.add("Some relationships are like tom and Jerry, they irritate each other, they tease each other, but they still can’t live without each other..");
        englist.add("I like kids, but I don’t think I could eat a whole one.");
        englist.add("Do you have the time? ………………… O No, the time to write down my number? :)");
        englist.add("Perfect boyfriend : Does not drink, does not smoke, does not cheat and also Does not exist :P");
        englist.add("All work and no play, will make you a manager.");
        englist.add("When we are bored we get on Facebook, then we get bored on Facebook so we get off then 15 min later back on. its an endless cycle..");
        englist.add("I thinks my neighbor just caught me stealing his Wi-Fi internet.");
        englist.add("If people could read my mind, I’d get punched in the face a lot.");
        englist.add("Insult and wife are somewhat similar....They always look good...If it is not yours!!!!");
        englist.add("At least mosquitos are attracted to me.");
        englist.add("That awkward moment when somebody is doing dishes and you slowly put another dish in the sink.");
        englist.add("Beauty isn’t measured by outer appearance and what clothes we wear, but what we are inside ..So, try going out naked tomorrow and see the admiration!");
        englist.add("You actually have friends? Yeah bro, all 10 seasons on DVD.");
        englist.add("Is it rude to throw a breath mint in someone’s mouth while they are talking?");
        englist.add("I`m not single. I`m in a long standing relationship with fun and freedom.");
        englist.add("Sorry about those texts I sent you last night, my phone was drunk.");
        englist.add("If you tell the boss you were late for work because you had a flat tire, the very next morning you will have a flat tire.");
        englist.add("A husband is someone who, after taking the trash out, gives the impression he just cleaned the whole house.");
        englist.add("If time does not wait for you, don’t worry. Just remove the battery from the clock and enjoy life.");
        englist.add("Dear Google: They are only using you to get to me. Sincerely Wikipedia");
        englist.add("Excuse me is your last name Gillette? …because you are the best a man can get!");
        englist.add("Ever read a book that changed your life? Me neither.");
        englist.add("Some people should have multiple Facebook accounts to go along with their multiple personalities.");
        englist.add("When I was born I was so surprised I didn’t talk for a year and a half.");
        englist.add("I’ve had a horribly busy day converting oxygen into carbon dioxide. :)");
        englist.add("Death is God’s way of saying you are fired. Suicide is humans way of saying, I quit.");
        englist.add("Save a horse, ride a cowboy.");
        englist.add("The only reason god made cousins so that parents can compare our marks.");
        englist.add("I’ll be a billionaire once I’m done inventing this device that lets you punch people in the face over the Internet.");
        if (isNetworkConnected()) {
            rajputlist.setVisibility(View.VISIBLE);
            Net_connection.setVisibility(View.GONE);

        } else {
            rajputlist.setVisibility(View.GONE);
            Net_connection.setVisibility(View.VISIBLE);
        }
        rjptadapter = new Shayri_Adapt(getActivity(), englist, "rjpthindi");
        rajputlist.setAdapter(rjptadapter);

        return view;
    }

    private boolean isNetworkConnected() {
        ConnectivityManager cm = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);
        return cm.getActiveNetworkInfo() != null && cm.getActiveNetworkInfo().isConnected();
    }

}