package ind.apptech.captionsforinstagram.fragment;

import android.content.Context;
import android.net.ConnectivityManager;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.RecyclerView;
import androidx.recyclerview.widget.StaggeredGridLayoutManager;

import ind.apptech.captionsforinstagram.Shayri_Adapt;
import com.apptech.captionsforinstagram.R;

import java.util.ArrayList;

public class Life extends Fragment {

    RecyclerView englishlists;
    private RecyclerView.LayoutManager layoutManager;
    Shayri_Adapt rjptadapter;
    ArrayList<String> englist = new ArrayList<>();
    LinearLayout Net_connection;

    public Life() {
        // Required empty public constructor
    }

    public static Life newInstance(String param1, String param2) {
        Life fragment = new Life();
        Bundle args = new Bundle();
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.hindi_shayri, container, false);

        englishlists = (RecyclerView) view.findViewById(R.id.English_list);
        Net_connection = view.findViewById(R.id.Net_connection);
        layoutManager = new StaggeredGridLayoutManager(1, StaggeredGridLayoutManager.VERTICAL);
        englishlists.setLayoutManager(layoutManager);
        englist = new ArrayList<>();

        englist.add("Life is beautiful if you know where to look...");
        englist.add("Life is not about waiting for the storms to pass.. It's about learning how to dance in the rain");
        englist.add("Life is unexplainable. So, don't try to explain it. Just live it");
        englist.add("A life Spent Making Mistakes Is Not Only More Honorable, But More Useful Than A Life Spent Doing Nothing.");
        englist.add("You can teach math science history philosophy but you can’t teach common sense.");
        englist.add("Life Isn't About What Happens To You, It's About How You Handle What Happens...");
        englist.add("Anything can happen when you take a chance.");
        englist.add("3 steps to move on. CTRL + ALT + DEL. Control yourself, look for an alternate solution & delete the situation that hurts you.");
        englist.add("The single and most dangerous word to be spoken in business is no. The second most dangerous word is yes. It is possible to avoid saying either.");
        englist.add("Best Advice: Silence is the best answer for all questions and smiling is the best reaction in all situations.");
        englist.add("life is about appreciating what you have, and waiting patiently for what you will get..");
        englist.add("I wish memories were text messages...you could delete the ones you don't want and keep the special ones forever!!!");
        englist.add("Life is like photography, we use the negatives to develop");
        englist.add("Promise could be make, but should never be brake");
        englist.add("Life is short, but glory might be eternal.");
        englist.add("Listen to your own voice, your own soul, too many people listen to the noise of the world, instead of themselves.");
        englist.add("Don't go out there and search, because you won't find it. Don't go sit there and wait, because it won't come to you. Just live your life and see what will cross your path");
        englist.add("Don't take life too seriously!! and don't worry about what's hidden for you in the future.. always remember, it just can't get worse.");
        englist.add("Breathe. It's just a bad day, not a bad life.");
        englist.add("The worst thing to be without.... Hope");
        englist.add("The average woman would rather have beauty than brains, because the average man can see better than he can think.");
        englist.add("Be careful who you trust and tell your problems to. Everyone who smiles at you is not your friend.");
        englist.add("Not everything you have stays forever. But there are things you would be glad to fight for just so you can have them longer.");
        englist.add("Life is entertaining, don't be afraid to laugh.");
        englist.add("Life gives you lots of chances to screw up...");
        englist.add("Great things happen when you least expect them");
        englist.add("Build a ship before you burn a bridge.");
        englist.add("Stop doing PERMANENT things with TEMPORARY people!!!");
        englist.add("Who says I'm alone???? I am always with me :-)");
        englist.add("Some people do anything and everything for attention.");
        englist.add("When you take things for granted, those things eventually get taken..");
        englist.add("Remember… every thing in life is a Choice, and every Choice comes with a Consequence, whether good or bad, Stop and think before you Choose your Consequence!");
        englist.add("You try so hard to believe that everything happens for a reason, yet there is  not one reason in the world that could satisfy you");
        englist.add("Good or bad, it was another piece to the puzzle of your life.");
        englist.add("Everything may be pre-written but nothing can be rewritten!");
        englist.add("There are two ways of looking at life, first is to see it coming and second is to see it going.");
        englist.add("The best revenge is looking good and being happy.");
        englist.add("Life is an effort that derives the best practice.");
        englist.add("Practice and creativity are the best teachers in the school of life.");
        englist.add("Who are you to judge the life i live? I know I am not perfect, and I don't live to be. But before you start pointing your fingers, make sure your hands are clean");
        englist.add("Anything in life that leaves butterflies in your stomach is worth experiencing");
        englist.add("I've been let down, put down, and knocked down, but I'M STILL STANDING");
        englist.add("I just want a person to come into my life and make me say Wow! instead of Why?");
        englist.add("There can be no Courage unless you're scared.");
        englist.add("live your dreams , don't dream your life .");
        englist.add("If you don't value life, you don't deserve it.");
        englist.add("Take the first step in faith. You don't have to see the whole staircase, just take the first step.");
        englist.add("No matter how many gorgeous faces you set your eyes upon, if you already set your heart for someone, you will hardly notice anyone.");
        englist.add("If someone really loves you, they wouldn’t let you slip away no matter how hard the situation is.");
        englist.add("The most beautiful thing in life is to build a bridge of hope on a sea of despair");
        englist.add("You only live once, but if you do it right, once is enough.");
        englist.add("Life is truly beautiful only when there's a tragedy in it.");
        englist.add("Don't sweat it or regret it, just move on and forget it.");
        englist.add("What people say to your face is not a problem. The problem is what they say behind your back.");
        englist.add("No one can go back and make a brand new start, however anyone can start from now and make a brand new ending.");
        englist.add("The smallest deed is better than the greatest intention.");
        englist.add("I'm not sure if life is passing me by or trying to run me over.");
        englist.add("Everything has been figured out, except the purpose of life!");
        englist.add("Trade expectations for appreciation.");
        englist.add("A day without laughter is a day wasted");
        englist.add("Sometimes its not the person you miss, but the feelings and moments you has when you were with them.");
        englist.add("Life should be measured with deeds, not years.");
        englist.add("If you do not ask, the answer will always be No.");
        englist.add("Courage is not having the strength to go on, its going on when you don't have the strength.");
        englist.add("Success is the Best Revenge");
        englist.add("Listen to what you know instead of what you fear.");
        englist.add("There is no greatness without passion to be great, whether it's the aspiration of an athlete or an artist, a scientist, a parent, or a businessperson.");
        englist.add("The people who want to stay in your life will always find a way.");
        englist.add("The past cannot be changed, forgotten, edited or erased. It can only be accepted.");
        englist.add("The darkest hours hold the brightest dreams.");
        englist.add("Don't wait for it to happen, make it happen.");
        englist.add("Whatever you do, good or bad, people will always have something negative to say");
        englist.add("Care less, smile more.");
        englist.add("Don't hurt others just because you're hurt.");
        englist.add("Boundaries help us know who we are, as well as who we are not");
        englist.add("Life devoted to pleasures without reason and morality, has no value.");
        englist.add("Life is meant to be lived by facing the challenges it brings.");
        englist.add("Never stress over over what you can't control..");
        englist.add("You don't become what you want, you become what you believe.");
        englist.add("Some people are actually so lucky, be grateful for what you've got  ... it can all be taken away in a second.");
        englist.add("If you're Crying Inside, Let It Out");
        englist.add("If you like me, tell Me. if you miss me show it and if you love me, PROVE IT.");
        englist.add("I do not think there is any other quality so essential to success of any kind as the quality of perseverance. It overcomes almost everything, even nature.");
        englist.add("What seems like the right thing to do could also be the hardest thing you have ever done in your life.");
        englist.add("From the worst moments you can learn the most.");
        englist.add("Life is a gift, appreciate it");
        englist.add("Love yourself in people for your life is nothing without them.");
        englist.add("Everything happens for a reason. Maybe you don't see the reason right now, but when it is finally revealed..it will blow you away.");
        englist.add("Promises are just lies tied in a pretty bow..");
        englist.add("Life's more fun when you're weird.");
        englist.add("Looks fade, but personality lasts forever.");
        englist.add("Those have a short Lent who owe money to be paid at Easter.");
        englist.add("A person's success depends on their commitment.");
        englist.add("Not everyone that looks good to you is good for you.");
        englist.add("One day, we will look back to this and say wow those were the days");
        englist.add("Life is a wonderful adventure.");
        englist.add("One day your life will flash before your eyes. Make sure it's worth watching.");
        englist.add("Never make permanant decisions on temporary feelings.");
        englist.add("Life doesn't give you what you want. It gives you what you work for.");
        englist.add("The only people you should allow in your life are the ones that prove they deserve to be.");
        englist.add("My insomnia is so bad that even when I do sleep I dream about lying awake.");
        englist.add("Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts");
        englist.add("Age is just a damn number, it doesn't stop you from loving someone");
        englist.add("Bad decisions make good stories");
        englist.add("The hardest thing in life is letting go of what you thought was real.");
        englist.add("The worst thing in life is that it passes.");
        englist.add("Don't say what you don't mean.");
        englist.add("It's not about saying the right things, it's about doing the right things.");
        englist.add("A life without challenge would be like going to school without lessons to learn. Challenges come not to depress or get you down, but to master and to grow and to unfold your abilities.");
        englist.add("They ignore you now but they will need you later, thats life.");
        englist.add("People who are attracted to you because of your pretty face or nice body won't be by your side forever. But the people who can see how beautiful your heart is will never leave you.");
        englist.add("Before you react, think. Before you quit, try.");
        englist.add("The essence of the faith is that it gives such a meaning to a life that can't be destroyed by the death.");
        englist.add("Never give your secret to anyone because if you can’t keep it to yourself don’t expect others to.");
        englist.add("You'll never Leave Where You Are Until You Decide Where You'd Rather Be.");
        englist.add("Greater things are yet to come...");
        englist.add("Lying won't make the truth go away, it just postpones it.");
        englist.add("Personality is like a haircut, once you have that distinctive style you instantly stand out.");
        englist.add("I wonder what the person I’m going to marry is doing right now.");
        englist.add("I'm crazy because I like having fun..");
        englist.add("Truth and honest life is the goal of my thoughts.");
        englist.add("Some relations are like TOM & JERRY. They tease eachother but can’t live without eachother.");
        englist.add("My formula for living is quite simple. I get up in the morning and I go to bed at night. In between, I occupy myself as best I can.");
        englist.add("May you follow your dreams and always believe in yourself. Keep your eyes on the stars and hope in your heart.");
        englist.add("You’re always loved by me in ways you’ll never see.");
        englist.add("When your dreams turn to dust, vacuum.");
        englist.add("Life always has many things to bring you down. But, what can really bring you down is your attitude.");
        englist.add("You were born because you are going to be important to someone.");
        englist.add("Many people get fake when life gets real.");
        englist.add("Jealousy is vanity of the flesh.");
        englist.add("Don't over think it. Just begin.");
        englist.add("Harsh words hurt feelings but silence breaks hearts.");
        englist.add("Distance means so little when someone means so much.");
        englist.add("When someone loves you they don’t have to say it; you can tell by the way they treat you.");
        englist.add("Every day is Remembrance Day. Lest we forget");
        englist.add("Life is hard, it's even harder if you are stupid.");
        englist.add("For some people, sport becomes the only way of thinking.");
        englist.add("We fear rejection, want attention, crave affection and dream of perfection.");
        englist.add("No trust, no relationship.");
        englist.add("LIFE is a Good thing, I suggest you get one.");
        englist.add("You need to be perfectly happy just on your own.");
        englist.add("There is nothing more exciting in the world, but people.");
        englist.add("When life comes at you, come back twice as hard");
        englist.add("Time, you can't keep it, but you can spend it.");
        englist.add("Life is a difficult test and the first hundred years are the most difficult.");
        englist.add("Life is too short to argue and fight. Count your blessings, value your friends and move on your head held high and a smile for everyone. (:");
        englist.add("In the beginning, I just waited for the end");
        englist.add("It is not length of life, but depth of life.");
        englist.add("Life is too short to wake up with regrets.");
        englist.add("Life is a journey with problems to solve, lessons to learn but most of all, experiences to enjoy.");
        englist.add("People don’t always need advice. Sometimes all they need is a hand to hold, ear to listen and heart to understand.");
        englist.add("I don't suffer from insanity, I enjoy every minute of it.");
        englist.add("Life is like the ocean. It can be calm and still or rough and rigid but in the end, it is always beautiful.");
        englist.add("Life is an option until you make it your highest priority.");
        englist.add("For me to live means to work.");
        englist.add("You just have to realize...people are going to stay in our hearts, even when they're not in our lives.");
        englist.add("When the well's dry, we know the worth of water.");
        englist.add("Don't let anyone ever make you feel like you don't deserve what you want");
        englist.add("Forget being serious..Let's just have fun.");
        englist.add("The sure way to be disappointed is to trust easily.");
        englist.add("When you talk, you repeat what you already know; when you listen, you often learn something.");
        englist.add("Use your energy wisely.");
        englist.add("Don't stress over what could've been, chances are if it should've been, it would've been.");
        englist.add("And at the end of the day, you either focus on what separated you, or what held you together");
        englist.add("Nothing ever happens like you imagine it will.");
        englist.add("I have a very good life - I'm lucky enough not to be deprived.");
        englist.add("Be nice to nerds. Chances are you'll end up working for one.");
        englist.add("If your dreams don't scare you, they're not big enough.");
        englist.add("Life is an opportunity, Capture it !");
        englist.add("I hope and pray that everything works out for you, that the pain you feel will leave, any stress or uncertainty will melt away, and everything that you strive for will fall into place.");
        englist.add("The first duty of a human being is fighting with Nature for his own and other's lives.");
        englist.add("Smile and enjoy life.");
        englist.add("Follow your heart, but take your brain with you");
        englist.add("I believe life is an intelligent thing: that things aren't random.");
        englist.add("Faith makes things possible, not easy.");
        englist.add("Each new day greets us with no rules...");
        englist.add("A real woman isn't perfect. A perfect woman isn't real. All that matters is that her spirit and heart are real. If you can't handle that, then maybe you're not being real where it counts");
        englist.add("Never promise what you can't deliver.");
        englist.add("If good things come to those who wait, something spectacular must be coming my way.. .. I've been waiting long enough");
        englist.add("He who has learned to disagree without being disagreeable has discovered the most valuable secret of a diplomat.");
        englist.add("Life's tragedy is that we get old too soon and wise too late");
        englist.add("Life's a garden. Dig it.");
        englist.add("Life is a comedy for those who think and a tragedy for those who feel.");
        englist.add("Life is not measured by the number of breaths we take, but by the moments that take our breath away.");
        englist.add("Each day is a new beginning.");
        englist.add("There's no going back. I've made my choices and by making those choices, I chose to move on");
        englist.add("You can`t face the problem if the problem iz your face.");
        englist.add("The best things in life are the people you love, the places you have seen and the memories you have made along the way.");
        englist.add("Pain is inevitable. Suffering is optional");
        englist.add("We don't know what we've been missing until it arrives.");
        englist.add("Life is too short to remove USB safely");
        englist.add("If you cant live for today, live for tomorrow.");
        englist.add("Never turn your back on people just because you found a new way to do things....A detour could always pop up and the people you turned on may be the road you have to take");
        englist.add("If you have no joke to tell, laugh.");
        englist.add("If you have nothing to think of, imagine one.");
        englist.add("Fear is nothing but the anticipation of pain.");
        englist.add("Expect the best. Prepare for the worst. Capitalize on what comes.");
        englist.add("If there is one lesson I am happy to take from life it is this. Life can tear you apart it can rip you end from end. But even with a broken heart we can prevail, humans are amazing creatures and that is what makes this journey worth it. Even if the path crosses into hell it is still worth the ride.");
        englist.add("Always remember to smile. You may not know it, but someone might be dying to see that smile everyday.");
        englist.add("The secret to a rich life is to have more beginnings than endings.");
        englist.add("There is Hell in Hello and Good in Goodbye. That's why you shouldn't be afraid of Goodbye but careful with the Hello");
        englist.add("Forgive someone because you believe they are truly sorry, not just because you just want to keep them in your life.");
        englist.add("Accept that some days you're the pigeon, and some days you're the statue.");
        englist.add("You have to know how to accept rejection and reject acceptance.");
        englist.add("The richest man is not he who has the most, but he who needs the least.");
        englist.add("Sometimes people try to expose what’s wrong with you because they can’t handle everything that’s right about you.");
        englist.add("True friends are there for you no matter what.");
        englist.add("Life is like photography, you use the negatives to develop");
        englist.add("Without the dark, we would never see the stars.");
        englist.add("if you understand life, you need a reality check.");
        englist.add("When we love, it is not necessary to understand what is happening outside, because everything happens inside us instead.");
        englist.add("Don't judge a book by its cover. Because what you see on the outside, could be a whole different story on the inside");
        englist.add("Give thanks for a little and you will find a lot.");
        englist.add("She couldn't see the light at the end of the tunnel, only because she closed her eyes");
        englist.add("There's no need to rush. If it's meant to happen, it'll happen.");
        englist.add("It takes a second to make a mistake but a lifetime to forget it was your fault.");
        englist.add("Winners make it happen. Losers let it happen.");
        englist.add("If you see nothing wrong with settling for less, then maybe you don't deserve better.");
        englist.add("It will be worth it to be with someone who knows your worth.");
        englist.add("In order to overcome the difficulties of life Nature has gifted us with a family.");
        englist.add("Living is easy with your eyes closed..");
        englist.add("Miracles happen, just Believe and Breathe");
        englist.add("No Struggle , No Progress");
        englist.add("History is the sum total of things that could have been avoided.");
        englist.add("Everything happens for a reason");
        englist.add("The road to success is always under construction");
        englist.add("Our life is what we think it is.");
        englist.add("When you pray, God answers in three ways: He says yes and gives what you ask for. He may give you something better. Or he says no, just be patient and I will give you what you have been wanting on for so long.");
        englist.add("The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint to keep from meddling with them while they do it.");
        englist.add("Life is not about making yourself feel important, it is about how important you can make others feel.");
        englist.add("The old horse may die in someone's keeping.");
        englist.add("The best thing about a picture is that it never changes even when the people in it do.");
        englist.add("Life is too short to wake up in the morning with regrets. So love the people who treat you right, forget about the ones who don’t and believe that everything happens for a reason.");
        englist.add("At one point in your life you either have the thing you want or the reasons why you don't");
        englist.add("The fashionable prejudice against eating mustard to lamb and mutton is absurd.");
        englist.add("Learn to appreciate what you have before time forces you to appreciate what you had");
        englist.add("You want to go to the mall - Someone is looking for anything they can wear just to stay warm.");
        englist.add("Life begins on the other side of despair.");
        englist.add("Every day may not be good, but there's something good in everyday");
        englist.add("Take control and make it happen.");
        englist.add("If we ever meet again, you'd better start running.");
        englist.add("Love bears all things, believes all things, hopes all things, endures all things.");
        englist.add("In life you’ll realize there is a purpose for everyone you meet. Some will test you, some will teach you, and some will use you. But most importantly, some will bring out the best in you.");
        englist.add("Your life is what your thoughts make it.");
        englist.add("if you have nothing nice to say, say nothing");
        englist.add("Chaos creates life. Order creates habit");
        englist.add("I know life was never meant to be easy.. but i never thought it would be this hard.");
        englist.add("If you are going to talk, let it mean something. People talk and spread lies/rumors, just to see who's miserable enough to listen, All you end up saying is a lot of nothing to no one.");
        englist.add("Life is like riding a bicycle. To keep your balance, you must kepp moving!!!!");
        englist.add("If you are successful, you will win some false friends and some true enemies. Succeed anyway.");
        englist.add("Friendship isn't a big thing, its a million little things");
        englist.add("Follow your heart and you will never lose your way.");
        englist.add("Live because there's a reason to, not just because you are alive.");
        englist.add("Know yourself, and know your opponent. They are never as strong as you think, and never as weak either.");
        englist.add("I laugh so hard tears run down my legs.");
        englist.add("In life there are many people who gave up fighting rather than those who were defeated.");
        englist.add("There is always, always, always something to be thankful for!");
        englist.add("Looking good is the best revenge.");
        englist.add("Use your energy on productive things!");
        englist.add("Control success before it controls you.");
        englist.add("A lie may take care of the present, but it has no future...");
        englist.add("Blood is thicker than water.");
        englist.add("Take chances. Chase your dreams. Don't play safe and be boring. Start living!");
        englist.add("A clean desk is a sign of a sick mind.");
        englist.add("Lose your pride, lose your patience, lose your mind. But whatever you do, don't lose hope.");
        englist.add("NEVER settle for less than you deserve..");
        englist.add("In the book of life, the most important thing is not to lose your place");
        englist.add("Life is really simple, but we insist on making it complicated.");
        englist.add("Freedom for the pike is death to the minnow");
        englist.add("Better to light a candle than to curse the darkness.");
        englist.add("Even behind the grayest cloud, lies one beautiful blue sky.");
        englist.add("Be who you are and say what you feel because those who mind don't matter and those who matter don't mind.");
        englist.add("People will treat you the way you let them.");
        englist.add("Life is too important to be taken seriously");
        englist.add("Truth is the only safe ground to stand on.");
        englist.add("The only important house to clean is your mind.");
        englist.add("Every great achievement was once considered impossible.");
        englist.add("If someone is bringing you down, cut them out of your life. It's that simple.");
        englist.add("Luck, it is said, dislikes working double shifts.");
        englist.add("Alcohol is an anesthesia for life.");
        englist.add("The greatest and the most divine feature of the man is the ability to forgive and pity.");
        englist.add("Life is short, Don't ever waste it.");
        englist.add("Sometimes we waste too much time to think about someone that does not think about us for 1 second.");
        englist.add("Accept what you cant change, and change what you cant accept.");
        englist.add("Everyone is handsome and beautiful...");
        englist.add("The pine stays green in winter...Wisdom in hardship.");
        englist.add("Apology accepted, trust denied.");
        englist.add("We could all take a lesson from crayons: some are sharp, some are beautiful, some have weird names, and all are different colors, but they still learn to live in the same box.");
        englist.add("Life comes full circle.");
        englist.add("Before I criticize someone, I walk a mile in their shoes. That way, if they get angry, they are a mile away and barefoot.");
        englist.add("Never lose hope. Never lose faith.");
        englist.add("Your life is a book; make it a bestseller.");
        englist.add("Smart listens to the head. Stupid listens to the heart");
        englist.add("I can't live without beauty; This is my weakness towards certain people.");
        englist.add("We only have one life to live so we have to live it the best we can.");
        englist.add("Most people don't notice what you do until you stop doing it.");
        englist.add("Loving is the most CREATIVE force in the universe..The memory of loving, the most destructive.");
        englist.add("At the end of the day before you close your eyes, be content with were you've been, and proud of who you are!");
        englist.add("I speak to everyone in the same way, whether he is the garbage man or the president of the university.");
        englist.add("I didn't think it was possible to find someone more confusing than me. Then, you came along.");
        englist.add("Sometimes you put walls up not to keep people out, but to see who cares enough to break them down.");
        englist.add("Sometimes, the questions are more important than the answers.");
        englist.add("There are many things that we would throw away if we were not afraid that others might pick them up");
        englist.add("Life is the greatest journey you will ever go on");
        englist.add("My life isn't perfect, but it does have perfect moments");
        englist.add("A bad word whispered will echo a hundred miles");
        englist.add("Just because something good ends doesn't mean something better won't begin.");
        englist.add("Write it on your heart that every day is the best day of the year.");
        englist.add("Life is not the amount of breaths you take, its the moments that take your breath away.");
        englist.add("Every night we go to bed without any assurance of being alive the next morning but still we set the alarm to wake up.. That’s called hope.");
        englist.add("A true man doesn't promise, he commits...A true woman doesn't demand, she thanks");
        englist.add("Learn how to be happy with what you have while you pursue all that you want.");
        englist.add("What made you happy once, might not make you happy now.");
        englist.add("Desires are the half of our lives, indifference is the half of death.");
        englist.add("Step with care and great tact, and remember that Life's a Great Balancing Act.");
        englist.add("Life has many different chapters for us. One bad chapter doesn't mean the end of the book.");
        englist.add("To be sure of hitting the target, shoot first and call whatever you hit the target.");
        englist.add("The road I chose is my own, and I will walk it proudly.");
        englist.add("Seize the day, embrace the present, enjoy life while you still can.");
        englist.add("Fatigue is the best pillow.");
        englist.add("When life's treating you like a rock......Become a stone.");
        englist.add("Most of the shadows of this life are caused by our standing in our own sunshine.");
        englist.add("Be thou faithful unto death, and I will give thee a crown of life.");
        englist.add("Early experience is formed due to strong memory.");
        englist.add("The sky is not blue, neither is the water...things are seldom what they seem to be, like people.");
        englist.add("Nothing ever goes away until it teaches us what we need to know.");
        englist.add("It doesn't matter what cards you're dealt in life, what matters is how well you play them.");
        englist.add("Do not regret growing older, it is a privilege denied to many.");
        englist.add("Don't respect someone for making a promise. Respect them for keeping it");
        englist.add("Take A Walk In My Shoes Before You Judge Me");
        englist.add("The heart feels what the eyes cannot see and knows what the mind cannot understand.");
        englist.add("This was a good dinner enough, to be sure; but it was not a dinner to ask a man to.");
        englist.add("Its better to walk away, than to tolerate nonsense.....");
        englist.add("A half truth is a whole lie.");
        englist.add("Life is very difficult when we are true to Everyone..");
        englist.add("Don't wish for it, work for it.");
        englist.add("Go for someone who isn't only proud to have you, but will also take every risk just to be with you!!");
        englist.add("Life is the art of drawing without an eraser");
        englist.add("It is not what you can do for your country, but what you can do for all of mankind.");
        englist.add("If you don't appreciate me, you don't deserve me.");
        englist.add("99% of what you worry about will never happen.");
        englist.add("Forgiving is easy, forgetting is hard.");
        englist.add("Life is a great story that someone ruined with the truth.");
        englist.add("It's never too late to be what you might have been.");
        englist.add("The life of every person is like a diary in which he means to write one story, and writes another.");
        englist.add("There is so much freedom, power, and restoration on the other side of letting go.");
        englist.add("An exit from somewhere is an entry to somewhere.");
        englist.add("People change. Feelings fade. Lovers drift. Friends leave. Friends become enemies. Lovers become strangers. You'll be judged. Life goes on.");
        englist.add("Nothing hurts more than realizing he meant everything to you. But you meant nothing to him.");
        englist.add("life is 2 short 2 be nothing but happy somebody sum where was wishing they could stayed just 1 more day with there family live it up like its your last day on this earth because we are none promised!!!!!!");
        englist.add("You never get a second chance to make a first impression !!!");
        englist.add("I'd rather have honest enemies than fake friends.");
        englist.add("Without trust, most things aren't possible.");
        englist.add("If u find the enemy fighting u then there is something unique, special n great about u, if the enemy never fights u then it means u have already compromised n joined him n u r no longer a threat to him, when the enemy brings a battle to u then understand that u r more than a conqueror n behind every battle there is a HIDDEN BLESSING!");
        englist.add("May my enemies' live long life to see my success.");
        englist.add("Running away from your problems is a race you’ll never win.");
        englist.add("Just because I wonder, doesn't mean I'm Lost");
        englist.add("Diligence is the mother of good luck.");
        englist.add("Everyone deserves a second chance, even the ones who didn't deserve the first.");
        englist.add("The big decisions start with the little decisions.");
        englist.add("Nothing is illegal if 100 businessmen decide to do it.");
        englist.add("Well done is better than well said.");
        englist.add("The only people you need in life are the ones that need you in theirs.");
        englist.add("Don't back down. Go around. Go around...");
        englist.add("Most of the things you worry about never happen.");
        englist.add("Every woman is wrong until she cries, and then she is right, instantly.");
        englist.add("One of the things that may get in the way of people   is that they're not in touch with their passion. If you're passionate about what it is you do, then you're going to be looking for everything you can to get better at it.");
        englist.add("Life is like a snow globe, often it's prettiest AFTER it's been turned upside-down");
        englist.add("I found the reason to smile, the day I found you.");
        englist.add("Life is better when you are laughing. Laugh as much as you breathe.");
        englist.add("Life is a chance, make sure you take it.");
        englist.add("There are two things needed in these days; first, for rich men to find out how poor men live, and second, for poor men to know how rich men work.");
        englist.add("Not life, but good life, is to be chiefly valued.");
        englist.add("You thought you were a nothing, but you're really a something, which makes you an anything.");
        englist.add("It's never too late to make it right.");
        englist.add("You can turn off the sun, But I'm still going to shine.");
        englist.add("Opportunities multiply as they are seized.");
        englist.add("One today is worth two tomorrows.");
        englist.add("Not the pleasures make value life, but life makes enjoy the pleasures.");
        englist.add("I am 99% sure that she doesn’t like me but it’s that 1% that keep me hangin on.");
        englist.add("Stay ready and you won't have to get ready.");
        englist.add("Nothing happens without risk");
        englist.add("Making a million friends is not a miracle...the miracle is to make such a friend who can stand with you when millions are against you");
        englist.add("Life is too short to spend it with people you don't like.");
        englist.add("If you are kind, people may accuse you of selfish, ulterior motives. Be kind anyway.");
        englist.add("Man cannot discover new oceans unless he has the courage to lose sight of the shore.");
        englist.add("Your thoughts are your life.");
        englist.add("You define your own life. Don’t let people write your script..");
        englist.add("Quitters never win and Winners never quit");
        englist.add("It is easier to prevent bad habits than to break them.");
        englist.add("Miserable people focus on what they hate about their life. Happy people focus on what they love about their life.");
        englist.add("What defines you is who you are when no one is looking.");
        englist.add("Be with the people who bring out the best in you.");
        englist.add("Some days you're the windshield, some days you're the bug");
        englist.add("Nothing ends nicely, that's why it ends.");
        englist.add("A goal properly set is halfway reached.");
        englist.add("When in doubt, don't.");
        englist.add("A bird in hand is safer than one overhead.");
        englist.add("Forget the rules..Lets just go crazy.");
        englist.add("It’s not a matter of finding the right person but its a matter of being the right person for the one you choose to love.");
        englist.add("Complaining never makes anything better.");
        englist.add("Everyone wants to be someone’s everything.");
        englist.add("Stay hungry, stay foolish.");
        englist.add("It`s not official until it`s on facebook.");
        englist.add("Someday you'll be everything to someone, just be patient.");
        englist.add("leave people better than how you found them. It always comes back to you - everything you do");
        englist.add("The energy of the mind is the essence of life.");
        englist.add("Never say never because in life, you always expect the unexpected.");
        englist.add("The healthiest form of revenge is self-improvement.");
        englist.add("The harder the struggle, the more glorious the triumph.");
        englist.add("Life goes on with or without you!");
        englist.add("I used to think that life had a plan for me, until I realized life had to be planned by me...");
        englist.add("The difference between CAN and CANNOT are only three letters. Three letter that determine your life direction.");
        englist.add("The measure of life is not in its duration but completeness.");
        englist.add("Be sincere; be brief; be seated.");
        englist.add("Either write something worth reading or do something worth writing.");
        englist.add("It is true....the world is a stage, that is why some act as if they are someone they are not and avoid who they truly are in order to put on a show worth watching..");
        englist.add("Where there is no struggle, there is no strength.");
        englist.add("Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes.");
        englist.add("The ugliest personality trait...Selfishness");
        englist.add("The truth is you don't know what is going to happen tomorrow. Life is a crazy ride, and nothing is guaranteed.");
        englist.add("Never forget the power you have to make a difference");
        englist.add("If your problem has a solution then...why worry about it? If your problem doesn't have solution then why worry about it?");
        englist.add("My silence dose not means I forgot..the mountain is silent but have volcano inside!!");
        englist.add("Don't take life too seriously, you'll never get out alive.");
        englist.add("It takes years to build friendship, years more to build love and only seconds to throw it all away.");
        englist.add("Change is the law of life. And those who look only to the past or present are certain to miss the future.");
        englist.add("Do I turn left, when nothing is right? Or do I turn right, when there's nothing left?");
        englist.add("There's a difference between hearing somebody and listening to them.");
        englist.add("Arguing with a fool only proves that there are two.");
        englist.add("I have a simple philosophy: Fill what's empty. Empty what's full. Scratch where it itches.");
        englist.add("Praying is like breathing, it should be essential to your life.");
        englist.add("What`s better? A lie that draws a smile or the truth that draws a tear?");
        englist.add("Stop worrying and be happy.");
        englist.add("I never dreamed about success. I worked for it.");
        englist.add("If you try to please everybody, nobody will like it.");
        englist.add("A friend in power is a friend lost.");
        englist.add("Life is short, why to waste in updating Status..");
        englist.add("The shin bone is a device for finding furniture in a dark room.");
        englist.add("Take a stand. Hold on tight. This is life and the ride might get a little bumpy.");
        englist.add("I'd learned that some things are best kept secret.");
        englist.add("I am not perfect but loving you makes me the best. ♥");
        englist.add("That moment when you give someone advice, they don't listen to you, then you sit back and watch everything you predicted happen.!! :|");
        englist.add("Because when you stop and look around, this life is pretty amazing");
        englist.add("Begin doing what you want to do now. We are not living in eternity. We have only this moment, sparkling like a star in our hand-and melting like a snowflake");
        englist.add("Just let go, there's beauty in the breakdown");
        englist.add("Challenges are what make life interesting and overcoming them is what makes life meaningful.");
        englist.add("It's only embarrassing if you care what people think.");
        englist.add("Care less, you'll be less stressed.");
        englist.add("I get enough exercise by just pushing my luck.");
        englist.add("Life, friends, is boring. We must not say so.");
        englist.add("People don't cheat by chance, they cheat by choice.");
        englist.add("Once you get what you want, You've got something to lose");
        englist.add("It's not whether you win or lose, it's how you place the blame.");
        englist.add("Never complain; never explain.");
        englist.add("I wish I could add myself as a friend. That's the only person I can depend on now a days.");
        englist.add("Smiling , It's easier than explaining why you're sad.");
        englist.add("No one is too busy, it's only a matter of priorities.");
        englist.add("Life's not about the people who act true to your face. It's about the people who remain true behind your back.");
        englist.add("People can say anything about you, but only you know the truth.");
        englist.add("Honesty is the best policy.");
        englist.add("Life is important when you have your family, friends, and love :)");
        englist.add("Words divide us, actions unite us.");
        englist.add("I might not be the best, but I’ll give you my best.");
        englist.add("There's a difference between being rude and being honest.");
        englist.add("There are two kinds of secrets. Those we keep from others...And those we hide from ourselves.");
        englist.add("You can't download a lifestyle.");
        englist.add("To think is easy. To act is hard. But the hardest thing in the world is to act in accordance with your thinking.");
        englist.add("What you can become depends upon what you can overcome.");
        englist.add("Memories will always stay. Thanks to you they are the best I've ever had.");
        englist.add("Do as you will yet harm none");
        englist.add("The most important trip you may take in life is meeting people half way.");
        englist.add("Life is what our feelings do with us.");
        englist.add("The most endangered species.........Dedicated leaders");
        englist.add("All that we are is the result of what we have thought");
        englist.add("Don't be afraid to speak from your heart.");
        englist.add("People change, love hurts, friends leave, things go wrong but just remember that life goes on.");
        englist.add("There is no future in the past. Move on. Life is too valuable to get stuck.");
        englist.add("Life is a challenge, meet it.");
        englist.add("You must decide who people that should be around you. It means you decide who you will be.");
        englist.add("Anger is one letter short of danger.");
        englist.add("Life is too short to hide your feelings. Don't be afraid to say what you feel.");
        englist.add("Good or bad, whatever you do will come back in one form or another; that would explain why the earth is round");
        englist.add("I dont care if anyone does not like me. I was not born in this world to entertain everyone.");
        englist.add("So many assume, So little know");
        englist.add("Being hurt doesn't give you the right to hurt anyone.");
        englist.add("It is impossible to dream too big.");
        englist.add("Pain happens when you care.");
        englist.add("While you’re busy looking for the perfect person, you’ll probably miss the imperfect person who could make you perfectly happy..");
        englist.add("I don't know what we're put on this planet to do but we're here damn it!");
        englist.add("May your heart be happy, may your days be bright, may your roads be smooth, may your burdens be light, may you find the dreams, may you touch the stars, may you never forget, how special you are.");
        englist.add("You can quit your job, but you can't quit your calling.");
        englist.add("When life changes to be more difficult, you must change yourself to be stronger.");
        englist.add("Pick up the bits and pieces and don't worry about how you're going to put them all together");
        englist.add("Don't wait for the right person to come into your life. Be the right person to come into someone's life.");
        englist.add("Don't ever be ashamed of who you are.");
        englist.add("If you had five minutes left to live; what would you do? The first thing that just came to your mind, go do it.");
        englist.add("Its better to let go with a smile in face than to hold on with tears in eyes.");
        englist.add("I've never regretted anything I've done. Only things that I haven't done.");
        englist.add("It's The Little Things That Makes Living Worthwhile.");

        if (isNetworkConnected()) {
            englishlists.setVisibility(View.VISIBLE);
            Net_connection.setVisibility(View.GONE);

        } else {
            englishlists.setVisibility(View.GONE);
            Net_connection.setVisibility(View.VISIBLE);
        }

        rjptadapter = new Shayri_Adapt(getActivity(), englist, "rjpthindi");
        englishlists.setAdapter(rjptadapter);

        return view;
    }

    private boolean isNetworkConnected() {
        ConnectivityManager cm = (ConnectivityManager) getActivity().getSystemService(Context.CONNECTIVITY_SERVICE);
        return cm.getActiveNetworkInfo() != null && cm.getActiveNetworkInfo().isConnected();
    }

}